// ATTENTION!
// THIS FILE IS GENERATED BY tool/genvercodes/main.go
// DO NOT EDIT MANUALLY

package actor

import (
	"fmt"

	actorstypes "github.com/filecoin-project/go-state-types/actors"
	"github.com/filecoin-project/lotus/chain/actors"
	"github.com/filecoin-project/lotus/chain/actors/builtin"

	exported0 "github.com/filecoin-project/specs-actors/actors/builtin/exported"
	miner0 "github.com/filecoin-project/specs-actors/actors/builtin/miner"

	exported2 "github.com/filecoin-project/specs-actors/v2/actors/builtin/exported"
	miner2 "github.com/filecoin-project/specs-actors/v2/actors/builtin/miner"

	exported3 "github.com/filecoin-project/specs-actors/v3/actors/builtin/exported"
	miner3 "github.com/filecoin-project/specs-actors/v3/actors/builtin/miner"

	exported4 "github.com/filecoin-project/specs-actors/v4/actors/builtin/exported"
	miner4 "github.com/filecoin-project/specs-actors/v4/actors/builtin/miner"

	exported5 "github.com/filecoin-project/specs-actors/v5/actors/builtin/exported"
	miner5 "github.com/filecoin-project/specs-actors/v5/actors/builtin/miner"

	exported6 "github.com/filecoin-project/specs-actors/v6/actors/builtin/exported"
	miner6 "github.com/filecoin-project/specs-actors/v6/actors/builtin/miner"

	exported7 "github.com/filecoin-project/specs-actors/v7/actors/builtin/exported"
	miner7 "github.com/filecoin-project/specs-actors/v7/actors/builtin/miner"

	miner8 "github.com/filecoin-project/go-state-types/builtin/v8/miner"

	miner9 "github.com/filecoin-project/go-state-types/builtin/v9/miner"

	miner10 "github.com/filecoin-project/go-state-types/builtin/v10/miner"

	miner11 "github.com/filecoin-project/go-state-types/builtin/v11/miner"
)

func init() {
	if len(actors.Versions) != len(Specs) {
		panic(fmt.Errorf("length of specs & versions are not equal, %d != %d", len(Specs), len(actors.Versions)))
	}

	if len(actors.Versions) != len(WatchOuts) {
		panic(fmt.Errorf("length of watch-out types & versions are not equal, %d != %d", len(WatchOuts), len(actors.Versions)))
	}

	for i := 1; i < len(WatchOuts); i++ {
		if len(WatchOuts[i]) != len(WatchOuts[i-1]) {
			panic(fmt.Errorf("number of watch-out types are differet for %d & %d, %d != %d", i-1, i, len(WatchOuts[i-1]), len(WatchOuts[i])))
		}
	}
}

var Specs = [][]builtin.RegistryEntry{
	builtin.MakeRegistryLegacy(exported0.BuiltinActors()),
	builtin.MakeRegistryLegacy(exported2.BuiltinActors()),
	builtin.MakeRegistryLegacy(exported3.BuiltinActors()),
	builtin.MakeRegistryLegacy(exported4.BuiltinActors()),
	builtin.MakeRegistryLegacy(exported5.BuiltinActors()),
	builtin.MakeRegistryLegacy(exported6.BuiltinActors()),
	builtin.MakeRegistryLegacy(exported7.BuiltinActors()),
	builtin.MakeRegistry(actorstypes.Version8),
	builtin.MakeRegistry(actorstypes.Version9),
	builtin.MakeRegistry(actorstypes.Version10),
	builtin.MakeRegistry(actorstypes.Version11),
}

var WatchOuts = [][]interface{}{
	[]interface{}{
		miner0.Deadline{},
		miner0.Partition{},
	},
	[]interface{}{
		miner2.Deadline{},
		miner2.Partition{},
	},
	[]interface{}{
		miner3.Deadline{},
		miner3.Partition{},
	},
	[]interface{}{
		miner4.Deadline{},
		miner4.Partition{},
	},
	[]interface{}{
		miner5.Deadline{},
		miner5.Partition{},
	},
	[]interface{}{
		miner6.Deadline{},
		miner6.Partition{},
	},
	[]interface{}{
		miner7.Deadline{},
		miner7.Partition{},
	},
	[]interface{}{
		miner8.Deadline{},
		miner8.Partition{},
	},
	[]interface{}{
		miner9.Deadline{},
		miner9.Partition{},
	},
	[]interface{}{
		miner10.Deadline{},
		miner10.Partition{},
	},
	[]interface{}{
		miner11.Deadline{},
		miner11.Partition{},
	},
}
