// ATTENTION!
// THIS FILE IS GENERATED BY tool/genvercodes/main.go
// DO NOT EDIT MANUALLY

package actorstate

import (
	"bytes"
	"fmt"

	"github.com/filecoin-project/go-address"
	"github.com/ipfs/go-cid"

	builtin6 "github.com/filecoin-project/specs-actors/v6/actors/builtin"

	power6 "github.com/filecoin-project/specs-actors/v6/actors/builtin/power"
	adt6 "github.com/filecoin-project/specs-actors/v6/actors/util/adt"

	"github.com/ipfs-force-community/londobell/common"
	"github.com/ipfs-force-community/londobell/racailum/segment/extract"
	"github.com/ipfs-force-community/londobell/racailum/segment/model"
	"github.com/ipfs-force-community/londobell/racailum/segment/model/schema"
)

func init() {
	mustRegisterRegularExtractor("ClaimedPowerV6", extractClaimedPowerV6)

	schema.Register(
		schema.Model{
			Name: "claimed-power-v6",
			D: &model.ClaimedPower{
				Detail: &power6.Claim{},
			},
		},
	)
}

func extractClaimedPowerV6(ctx *extract.Ctx, res *extract.Res, head *common.ActorHead, pst *power6.State) error { // nolint: deadcode

	claims, err := adt6.AsMap(ctx.D.ActorStore(ctx.C), pst.Claims, builtin6.DefaultHamtBitwidth)

	if err != nil {
		return fmt.Errorf("construct adt.Map for Claims in *power6.State: %w", err)
	}

	out := &power6.Claim{}
	var buf bytes.Buffer
	if err := claims.ForEach(out, func(keystr string) error {
		detail := *out
		if isEmptyOrZero(detail.RawBytePower) {
			return nil
		}

		buf.Reset()

		addr, err := address.NewFromBytes([]byte(keystr))
		if err != nil {
			return fmt.Errorf("parse addr from adt.Map key %s: %w", keystr, err)
		}

		id, err := genClaimedPowerID(&buf, keystr, &detail)
		if err != nil {
			return err
		}

		res.Docs = append(res.Docs, &model.ClaimedPower{
			ActorStateExBasic: model.ActorStateExBasic{
				ID:    id,
				Path:  []cid.Cid{head.Head, pst.Claims},
				Addr:  addr,
				Epoch: head.Epoch,
			},
			Detail: &detail,
		})

		*out = power6.Claim{}
		return nil
	}); err != nil {
		return err
	}

	return nil
}
