// ATTENTION!
// THIS FILE IS GENERATED BY tool/genvercodes/main.go
// DO NOT EDIT MANUALLY

package actorstate

import (
	"fmt"

	"github.com/filecoin-project/go-state-types/abi"
	"github.com/filecoin-project/go-state-types/big"
	"github.com/ipfs/go-cid"

	miner0 "github.com/filecoin-project/specs-actors/actors/builtin/miner"
	adt0 "github.com/filecoin-project/specs-actors/actors/util/adt"

	miner2 "github.com/filecoin-project/specs-actors/v2/actors/builtin/miner"
	adt2 "github.com/filecoin-project/specs-actors/v2/actors/util/adt"

	miner3 "github.com/filecoin-project/specs-actors/v3/actors/builtin/miner"
	adt3 "github.com/filecoin-project/specs-actors/v3/actors/util/adt"

	miner4 "github.com/filecoin-project/specs-actors/v4/actors/builtin/miner"
	adt4 "github.com/filecoin-project/specs-actors/v4/actors/util/adt"

	miner5 "github.com/filecoin-project/specs-actors/v5/actors/builtin/miner"
	adt5 "github.com/filecoin-project/specs-actors/v5/actors/util/adt"

	miner6 "github.com/filecoin-project/specs-actors/v6/actors/builtin/miner"
	adt6 "github.com/filecoin-project/specs-actors/v6/actors/util/adt"

	"github.com/ipfs-force-community/londobell/common"
	"github.com/ipfs-force-community/londobell/lib/mir"
	"github.com/ipfs-force-community/londobell/racailum/segment/extract"
	"github.com/ipfs-force-community/londobell/racailum/segment/model"
	"github.com/ipfs-force-community/londobell/racailum/segment/model/schema"
)

func init() {
	schema.Register(
		schema.Model{
			Name: "miner-funds",
			D:    &model.MinerFunds{},
		},
	)
}

func NewTokenAmountArr(length int) []abi.TokenAmount {
	s := make([]abi.TokenAmount, length, length)
	for i := range s {
		s[i] = abi.NewTokenAmount(0)
	}
	return s
}

func extractMinerFunds(ctx *extract.Ctx, res *extract.Res, head *common.ActorHead, st interface{}) error {
	if ticks := ctx.Opts.StateRegular.MinerFundsTicks; ticks > 0 && head.Epoch%(abi.ChainEpoch(ticks)*ctx.Opts.StateRegular.Interval) != 0 {
		return nil
	}

	tsRange := NormalEpochRange(head)
	vestInFuture := NewTokenAmountArr(len(tsRange))
	pledgeRelease := NewTokenAmountArr(len(tsRange))

	var detail model.MinerFundsDetail
	sum := abi.NewTokenAmount(0)

	switch st := st.(type) {
	case *miner0.State:
		if err := mir.Mirror(&detail, st); err != nil {
			return fmt.Errorf("mirroring *miner2.State: %w", err)
		}

		if !st.VestingFunds.Equals(emptyMinerStateV0.VestingFunds) {
			funds, err := st.LoadVestingFunds(adt0.WrapStore(ctx.C, ctx.D.ActorStore(ctx.C)))
			if err != nil {
				return fmt.Errorf("load vesting funds: %w", err)
			}

			for _, v := range funds.Funds {
				sum = big.Add(sum, v.Amount)
			}
		}

	case *miner2.State:
		if err := mir.Mirror(&detail, st); err != nil {
			return fmt.Errorf("mirroring *miner2.State: %w", err)
		}

		if !st.VestingFunds.Equals(emptyMinerStateV2.VestingFunds) {
			funds, err := st.LoadVestingFunds(adt2.WrapStore(ctx.C, ctx.D.ActorStore(ctx.C)))
			if err != nil {
				return fmt.Errorf("load vesting funds: %w", err)
			}

			for _, v := range funds.Funds {
				sum = big.Add(sum, v.Amount)
			}
		}

	case *miner3.State:
		if err := mir.Mirror(&detail, st); err != nil {
			return fmt.Errorf("mirroring *miner2.State: %w", err)
		}

		if !st.VestingFunds.Equals(emptyMinerStateV3.VestingFunds) {
			funds, err := st.LoadVestingFunds(adt3.WrapStore(ctx.C, ctx.D.ActorStore(ctx.C)))
			if err != nil {
				return fmt.Errorf("load vesting funds: %w", err)
			}

			for _, v := range funds.Funds {
				sum = big.Add(sum, v.Amount)
			}
		}

	case *miner4.State:
		if err := mir.Mirror(&detail, st); err != nil {
			return fmt.Errorf("mirroring *miner2.State: %w", err)
		}

		if !st.VestingFunds.Equals(emptyMinerStateV4.VestingFunds) {
			funds, err := st.LoadVestingFunds(adt4.WrapStore(ctx.C, ctx.D.ActorStore(ctx.C)))
			if err != nil {
				return fmt.Errorf("load vesting funds: %w", err)
			}

			for _, v := range funds.Funds {
				sum = big.Add(sum, v.Amount)
			}
		}

	case *miner5.State:
		if err := mir.Mirror(&detail, st); err != nil {
			return fmt.Errorf("mirroring *miner5.State: %w", err)
		}

		if isEmptyOrZero(detail.PreCommitDeposits) &&
			isEmptyOrZero(detail.LockedFunds) &&
			isEmptyOrZero(detail.FeeDebt) &&
			isEmptyOrZero(detail.InitialPledge) {
			return nil
		}

		if !st.VestingFunds.Equals(emptyMinerStateV5.VestingFunds) {
			funds, err := st.LoadVestingFunds(adt5.WrapStore(ctx.C, ctx.D.ActorStore(ctx.C)))
			if err != nil {
				return fmt.Errorf("load vesting funds: %w", err)
			}

			// assign vest in future
			for _, v := range funds.Funds {
				if v.Epoch < head.Epoch {
					continue
				}

				for j := range tsRange {
					if v.Epoch < tsRange[j] {
						vestInFuture[j] = big.Add(vestInFuture[j], v.Amount)
						break
					}
				}
			}
		}
		actStore := ctx.D.ActorStore(ctx.C)
		deadlines, err := st.LoadDeadlines(actStore)
		if err != nil {
			return fmt.Errorf("load deadlines failed: %w", err)
		}

		err = deadlines.ForEach(actStore, func(dlIdx uint64, dl *miner5.Deadline) error {
			if dl == nil {
				return nil
			}

			ps, err := dl.PartitionsArray(actStore)
			if err != nil {
				return fmt.Errorf("get dl partition failed: %w", err)
			}
			var part miner5.Partition
			dlInfo := miner5.NewDeadlineInfo(st.CurrentProvingPeriodStart(head.Epoch), dlIdx, head.Epoch).NextNotElapsed()
			quant := miner5.QuantSpecForDeadline(dlInfo)

			return ps.ForEach(&part, func(partIdx int64) error {
				expirations, err := miner5.LoadExpirationQueue(actStore, part.ExpirationsEpochs, quant, miner5.PartitionExpirationAmtBitwidth)
				if err != nil {
					return fmt.Errorf("failed to load expiration queue: %w", err)
				}

				for i := range tsRange {
					popped, err := expirations.PopUntil(tsRange[i])
					if err != nil {
						return fmt.Errorf("failed to pop expiration queue until %d: %w", tsRange[i], err)
					}

					pledgeRelease[i] = popped.OnTimePledge
				}

				return nil
			})
		})

		if err != nil {
			return fmt.Errorf("process sector pledge failed")
		}

	case *miner6.State:
		if err := mir.Mirror(&detail, st); err != nil {
			return fmt.Errorf("mirroring *miner6.State: %w", err)
		}

		if isEmptyOrZero(detail.PreCommitDeposits) &&
			isEmptyOrZero(detail.LockedFunds) &&
			isEmptyOrZero(detail.FeeDebt) &&
			isEmptyOrZero(detail.InitialPledge) {
			return nil
		}

		if !st.VestingFunds.Equals(emptyMinerStateV6.VestingFunds) {
			funds, err := st.LoadVestingFunds(adt6.WrapStore(ctx.C, ctx.D.ActorStore(ctx.C)))
			if err != nil {
				return fmt.Errorf("load vesting funds: %w", err)
			}

			// assign vest in future
			for _, v := range funds.Funds {
				if v.Epoch < head.Epoch {
					continue
				}

				for j := range tsRange {
					if v.Epoch < tsRange[j] {
						vestInFuture[j] = big.Add(vestInFuture[j], v.Amount)
						break
					}
				}
			}
		}
		actStore := ctx.D.ActorStore(ctx.C)
		deadlines, err := st.LoadDeadlines(actStore)
		if err != nil {
			return fmt.Errorf("load deadlines failed: %w", err)
		}

		err = deadlines.ForEach(actStore, func(dlIdx uint64, dl *miner6.Deadline) error {
			if dl == nil {
				return nil
			}

			ps, err := dl.PartitionsArray(actStore)
			if err != nil {
				return fmt.Errorf("get dl partition failed: %w", err)
			}
			var part miner6.Partition
			dlInfo := miner6.NewDeadlineInfo(st.CurrentProvingPeriodStart(head.Epoch), dlIdx, head.Epoch).NextNotElapsed()
			quant := miner6.QuantSpecForDeadline(dlInfo)

			return ps.ForEach(&part, func(partIdx int64) error {
				expirations, err := miner6.LoadExpirationQueue(actStore, part.ExpirationsEpochs, quant, miner6.PartitionExpirationAmtBitwidth)
				if err != nil {
					return fmt.Errorf("failed to load expiration queue: %w", err)
				}

				for i := range tsRange {
					popped, err := expirations.PopUntil(tsRange[i])
					if err != nil {
						return fmt.Errorf("failed to pop expiration queue until %d: %w", tsRange[i], err)
					}

					pledgeRelease[i] = popped.OnTimePledge
				}

				return nil
			})
		})

		if err != nil {
			return fmt.Errorf("process sector pledge failed")
		}

	}

	detail.VestInFuture = vestInFuture
	detail.PledgeRelease = pledgeRelease
	// all zero
	if isEmptyOrZero(detail.PreCommitDeposits) &&
		isEmptyOrZero(detail.LockedFunds) &&
		isEmptyOrZero(detail.FeeDebt) &&
		isEmptyOrZero(detail.InitialPledge) {
		return nil
	}

	id, err := GenRegularHeadID(head.Head, head.Addr, head.Epoch)
	if err != nil {
		return fmt.Errorf("generate regular id: %w", err)
	}

	res.Docs = append(res.Docs, &model.MinerFunds{
		ActorStateExBasic: model.ActorStateExBasic{
			ID:    id,
			Path:  []cid.Cid{head.Head},
			Addr:  head.Addr,
			Epoch: head.Epoch,
		},
		Detail: detail,
	})

	return nil
}
