// ATTENTION!
// THIS FILE IS GENERATED BY tool/genvercodes/main.go
// DO NOT EDIT MANUALLY

package actorstate

import (
	"fmt"

	"github.com/filecoin-project/go-address"
	"github.com/filecoin-project/go-state-types/abi"
	"github.com/ipfs/go-cid"

	verifreg0 "github.com/filecoin-project/specs-actors/actors/builtin/verifreg"
	adt0 "github.com/filecoin-project/specs-actors/actors/util/adt"

	"github.com/ipfs-force-community/londobell/common"
	"github.com/ipfs-force-community/londobell/racailum/segment/extract"
	"github.com/ipfs-force-community/londobell/racailum/segment/model"
	"github.com/ipfs-force-community/londobell/racailum/segment/model/schema"
)

func init() {
	mustRegisterRegularExtractor("VerifRegV0", extractVerifRegV0)

	schema.Register(
		schema.Model{
			Name: "verifreg",
			D:    &model.VerifiedRegistry{},
		},
	)
}

func extractVerifRegV0(ctx *extract.Ctx, res *extract.Res, head *common.ActorHead, st *verifreg0.State) error {
	if ticks := ctx.Opts.StateRegular.VerifRegTicks; ticks > 0 && head.Epoch%(abi.ChainEpoch(ticks)*ctx.Opts.StateRegular.Interval) != 0 {
		return nil
	}

	mapRoots := []struct {
		name string
		root cid.Cid
	}{
		{
			name: "Verifier",
			root: st.Verifiers,
		},
		{
			name: "VerifiedClient",
			root: st.VerifiedClients,
		},
	}

	for mi := range mapRoots {
		root := mapRoots[mi].root
		name := mapRoots[mi].name

		m, err := adt0.AsMap(ctx.D.ActorStore(ctx.C), root)
		if err != nil {
			return fmt.Errorf("construct adt.Map: %w", err)
		}

		out := &abi.StoragePower{}
		if err := m.ForEach(out, func(keystr string) error {
			datacap := *out
			if isEmptyOrZero(datacap) {
				return nil
			}

			addr, err := address.NewFromBytes([]byte(keystr))
			if err != nil {
				return fmt.Errorf("parse addr from adt.Map key %s: %w", keystr, err)
			}

			id, err := GenRegularHeadID(head.Head, addr, head.Epoch)
			if err != nil {
				return err
			}

			res.Docs = append(res.Docs, &model.VerifiedRegistry{
				ActorStateExBasic: model.ActorStateExBasic{
					ID:    id,
					Path:  []cid.Cid{head.Head, root},
					Addr:  addr,
					Epoch: head.Epoch,
				},
				Detail: model.VerifiedRegistryDetail{
					Type: name,
					Cap:  datacap,
				},
			})

			*out = abi.StoragePower{}
			return nil
		}); err != nil {
			return err
		}
	}

	return nil
}
