package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"text/template"

	"github.com/filecoin-project/lotus/chain/actors"
)

var attentionNote = []byte("// ATTENTION!\n// THIS FILE IS GENERATED BY tool/gentypes/main.go\n// DO NOT EDIT MANUALLY\n\n")

type verInfo struct {
	Ver        int
	ImportPath string
}

const (
	in  = "./cmd/londobell-api/templates/types.one.template"
	out = "./cmd/londobell-api/controller/adapter/types.go"
)

func main() {
	if err := generate(in, out); err != nil {
		fmt.Println("error:", err)
	}

}

func generate(in, out string) error {
	vers := make([]verInfo, len(actors.Versions))
	for i := range actors.Versions {
		ver := actors.Versions[i]
		inPath := "github.com/filecoin-project/specs-actors"
		inPath2 := "github.com/filecoin-project/go-state-types/builtin"
		if ver != 0 && ver < int(actors.Version8) {
			inPath = fmt.Sprintf("%s/v%d", inPath, ver)
		} else if ver >= int(actors.Version8) {
			inPath = fmt.Sprintf("%s/v%d", inPath2, ver)
		}

		vers[i] = verInfo{
			Ver:        ver,
			ImportPath: inPath,
		}
	}

	data, err := os.ReadFile(in)
	if err != nil {
		return fmt.Errorf("read file: %w", err)
	}

	t := template.New("types")
	t, err = t.Parse(string(data))
	if err != nil {
		return fmt.Errorf("parse template text: %w", err)
	}

	var outbuf bytes.Buffer
	outbuf.Write(attentionNote)

	err = t.Execute(&outbuf, map[string]interface{}{
		"Vers": vers,
	})
	if err != nil {
		return fmt.Errorf("render template: %w", err)
	}

	formatted, err := format.Source(outbuf.Bytes())
	if err != nil {
		return fmt.Errorf("format go source file for rendered file: %w", err)
	}

	err = os.WriteFile(out, formatted, 0644)
	if err != nil {
		return fmt.Errorf("write into out file %s: %w", out, err)
	}

	log.Printf("\tgenerated %s", out)

	return nil
}
