// ATTENTION!
// THIS FILE IS GENERATED BY tool/gentypes/main.go
// DO NOT EDIT MANUALLY

package adapter

import (
	"fmt"

	"github.com/filecoin-project/go-address"
	actorstypes "github.com/filecoin-project/go-state-types/actors"
	"github.com/filecoin-project/go-state-types/builtin"
	"github.com/filecoin-project/go-state-types/manifest"
	builtin0 "github.com/filecoin-project/specs-actors/actors/builtin"
	builtin2 "github.com/filecoin-project/specs-actors/v2/actors/builtin"
	builtin3 "github.com/filecoin-project/specs-actors/v3/actors/builtin"
	builtin4 "github.com/filecoin-project/specs-actors/v4/actors/builtin"
	builtin5 "github.com/filecoin-project/specs-actors/v5/actors/builtin"
	builtin6 "github.com/filecoin-project/specs-actors/v6/actors/builtin"
	builtin7 "github.com/filecoin-project/specs-actors/v7/actors/builtin"
	"github.com/ipfs/go-cid"

	"github.com/filecoin-project/lotus/chain/actors"
	"github.com/filecoin-project/lotus/chain/actors/adt"
	"github.com/filecoin-project/lotus/chain/actors/builtin/system"
)

func IsStoragePowerActor(c cid.Cid) bool {
	if name, _, ok := actors.GetActorMetaByCode(c); ok {
		if name != manifest.PowerKey {
			return false
		}
		return true
	}

	if c == builtin0.StoragePowerActorCodeID {
		return true
	}
	if c == builtin2.StoragePowerActorCodeID {
		return true
	}
	if c == builtin3.StoragePowerActorCodeID {
		return true
	}
	if c == builtin4.StoragePowerActorCodeID {
		return true
	}
	if c == builtin5.StoragePowerActorCodeID {
		return true
	}
	if c == builtin6.StoragePowerActorCodeID {
		return true
	}
	if c == builtin7.StoragePowerActorCodeID {
		return true
	}

	return false
}

func IsRewardActor(c cid.Cid) bool {
	if name, _, ok := actors.GetActorMetaByCode(c); ok {
		if name != manifest.RewardKey {
			return false
		}
		return true
	}

	if c == builtin0.RewardActorCodeID {
		return true
	}
	if c == builtin2.RewardActorCodeID {
		return true
	}
	if c == builtin3.RewardActorCodeID {
		return true
	}
	if c == builtin4.RewardActorCodeID {
		return true
	}
	if c == builtin5.RewardActorCodeID {
		return true
	}
	if c == builtin6.RewardActorCodeID {
		return true
	}
	if c == builtin7.RewardActorCodeID {
		return true
	}

	return false
}

func IsInitActor(c cid.Cid) bool {
	if name, _, ok := actors.GetActorMetaByCode(c); ok {
		if name != manifest.InitKey {
			return false
		}
		return true
	}

	if c == builtin0.InitActorCodeID {
		return true
	}
	if c == builtin2.InitActorCodeID {
		return true
	}
	if c == builtin3.InitActorCodeID {
		return true
	}
	if c == builtin4.InitActorCodeID {
		return true
	}
	if c == builtin5.InitActorCodeID {
		return true
	}
	if c == builtin6.InitActorCodeID {
		return true
	}
	if c == builtin7.InitActorCodeID {
		return true
	}

	return false
}

func IsStorageMarketActor(c cid.Cid) bool {
	if name, _, ok := actors.GetActorMetaByCode(c); ok {
		if name != manifest.MarketKey {
			return false
		}
		return true
	}

	if c == builtin0.StorageMarketActorCodeID {
		return true
	}
	if c == builtin2.StorageMarketActorCodeID {
		return true
	}
	if c == builtin3.StorageMarketActorCodeID {
		return true
	}
	if c == builtin4.StorageMarketActorCodeID {
		return true
	}
	if c == builtin5.StorageMarketActorCodeID {
		return true
	}
	if c == builtin6.StorageMarketActorCodeID {
		return true
	}
	if c == builtin7.StorageMarketActorCodeID {
		return true
	}

	return false
}

func IsVerifiedRegistryActor(c cid.Cid) bool {
	if name, _, ok := actors.GetActorMetaByCode(c); ok {
		if name != manifest.VerifregKey {
			return false
		}
		return true
	}

	if c == builtin0.VerifiedRegistryActorCodeID {
		return true
	}
	if c == builtin2.VerifiedRegistryActorCodeID {
		return true
	}
	if c == builtin3.VerifiedRegistryActorCodeID {
		return true
	}
	if c == builtin4.VerifiedRegistryActorCodeID {
		return true
	}
	if c == builtin5.VerifiedRegistryActorCodeID {
		return true
	}
	if c == builtin6.VerifiedRegistryActorCodeID {
		return true
	}
	if c == builtin7.VerifiedRegistryActorCodeID {
		return true
	}

	return false
}

func IsSystemActor(c cid.Cid) bool {
	if name, _, ok := actors.GetActorMetaByCode(c); ok {
		if name != manifest.SystemKey {
			return false
		}
		return true
	}

	if c == builtin0.SystemActorCodeID {
		return true
	}
	if c == builtin2.SystemActorCodeID {
		return true
	}
	if c == builtin3.SystemActorCodeID {
		return true
	}
	if c == builtin4.SystemActorCodeID {
		return true
	}
	if c == builtin5.SystemActorCodeID {
		return true
	}
	if c == builtin6.SystemActorCodeID {
		return true
	}
	if c == builtin7.SystemActorCodeID {
		return true
	}

	return false
}

func IsBurntFundsActor(addr address.Address) bool {
	if addr == builtin.BurntFundsActorAddr {
		return true
	}

	return false
}

func MakeSystemState(store adt.Store, c cid.Cid) (system.State, error) {
	if name, av, ok := actors.GetActorMetaByCode(c); ok {
		if name != manifest.SystemKey {
			return nil, fmt.Errorf("actor code is not system: %s", name)
		}

		switch av {

		case actorstypes.Version8:
			return system.MakeState(store, actorstypes.Version8, cid.Undef)
		case actorstypes.Version9:
			return system.MakeState(store, actorstypes.Version9, cid.Undef)
		}
	}

	if c == builtin0.SystemActorCodeID {
		return system.MakeState(store, actorstypes.Version0, cid.Undef)
	}
	if c == builtin2.SystemActorCodeID {
		return system.MakeState(store, actorstypes.Version2, cid.Undef)
	}
	if c == builtin3.SystemActorCodeID {
		return system.MakeState(store, actorstypes.Version3, cid.Undef)
	}
	if c == builtin4.SystemActorCodeID {
		return system.MakeState(store, actorstypes.Version4, cid.Undef)
	}
	if c == builtin5.SystemActorCodeID {
		return system.MakeState(store, actorstypes.Version5, cid.Undef)
	}
	if c == builtin6.SystemActorCodeID {
		return system.MakeState(store, actorstypes.Version6, cid.Undef)
	}
	if c == builtin7.SystemActorCodeID {
		return system.MakeState(store, actorstypes.Version7, cid.Undef)
	}

	return nil, fmt.Errorf("not system actor code: %v", c)
}
