// ATTENTION!
// THIS FILE IS GENERATED BY tool/gentypes/main.go
// DO NOT EDIT MANUALLY

package adapter

import (
	"context"
	"fmt"
	"github.com/ipfs-force-community/londobell/cmd/londobell-api/model"

	"github.com/filecoin-project/go-address"
	"github.com/filecoin-project/go-bitfield"
	"github.com/filecoin-project/go-state-types/abi"
	actorstypes "github.com/filecoin-project/go-state-types/actors"
	"github.com/filecoin-project/go-state-types/big"
	"github.com/filecoin-project/go-state-types/builtin"
	sbuiltin "github.com/filecoin-project/go-state-types/builtin"
	miner10 "github.com/filecoin-project/go-state-types/builtin/v10/miner"
	util10 "github.com/filecoin-project/go-state-types/builtin/v10/util"
	adt10 "github.com/filecoin-project/go-state-types/builtin/v10/util/adt"
	miner11 "github.com/filecoin-project/go-state-types/builtin/v11/miner"
	util11 "github.com/filecoin-project/go-state-types/builtin/v11/util"
	adt11 "github.com/filecoin-project/go-state-types/builtin/v11/util/adt"
	miner12 "github.com/filecoin-project/go-state-types/builtin/v12/miner"
	util12 "github.com/filecoin-project/go-state-types/builtin/v12/util"
	adt12 "github.com/filecoin-project/go-state-types/builtin/v12/util/adt"
	miner13 "github.com/filecoin-project/go-state-types/builtin/v13/miner"
	util13 "github.com/filecoin-project/go-state-types/builtin/v13/util"
	adt13 "github.com/filecoin-project/go-state-types/builtin/v13/util/adt"
	miner14 "github.com/filecoin-project/go-state-types/builtin/v14/miner"
	util14 "github.com/filecoin-project/go-state-types/builtin/v14/util"
	adt14 "github.com/filecoin-project/go-state-types/builtin/v14/util/adt"
	miner15 "github.com/filecoin-project/go-state-types/builtin/v15/miner"
	util15 "github.com/filecoin-project/go-state-types/builtin/v15/util"
	adt15 "github.com/filecoin-project/go-state-types/builtin/v15/util/adt"
	miner8 "github.com/filecoin-project/go-state-types/builtin/v8/miner"
	util8 "github.com/filecoin-project/go-state-types/builtin/v8/util"
	adt8 "github.com/filecoin-project/go-state-types/builtin/v8/util/adt"
	miner9 "github.com/filecoin-project/go-state-types/builtin/v9/miner"
	util9 "github.com/filecoin-project/go-state-types/builtin/v9/util"
	adt9 "github.com/filecoin-project/go-state-types/builtin/v9/util/adt"
	"github.com/filecoin-project/go-state-types/manifest"
	"github.com/filecoin-project/lotus/chain/types"
	builtin0 "github.com/filecoin-project/specs-actors/actors/builtin"
	miner0 "github.com/filecoin-project/specs-actors/actors/builtin/miner"
	adt0 "github.com/filecoin-project/specs-actors/actors/util/adt"
	builtin2 "github.com/filecoin-project/specs-actors/v2/actors/builtin"
	miner2 "github.com/filecoin-project/specs-actors/v2/actors/builtin/miner"
	adt2 "github.com/filecoin-project/specs-actors/v2/actors/util/adt"
	builtin3 "github.com/filecoin-project/specs-actors/v3/actors/builtin"
	miner3 "github.com/filecoin-project/specs-actors/v3/actors/builtin/miner"
	adt3 "github.com/filecoin-project/specs-actors/v3/actors/util/adt"
	builtin4 "github.com/filecoin-project/specs-actors/v4/actors/builtin"
	miner4 "github.com/filecoin-project/specs-actors/v4/actors/builtin/miner"
	adt4 "github.com/filecoin-project/specs-actors/v4/actors/util/adt"
	builtin5 "github.com/filecoin-project/specs-actors/v5/actors/builtin"
	miner5 "github.com/filecoin-project/specs-actors/v5/actors/builtin/miner"
	adt5 "github.com/filecoin-project/specs-actors/v5/actors/util/adt"
	builtin6 "github.com/filecoin-project/specs-actors/v6/actors/builtin"
	miner6 "github.com/filecoin-project/specs-actors/v6/actors/builtin/miner"
	adt6 "github.com/filecoin-project/specs-actors/v6/actors/util/adt"
	builtin7 "github.com/filecoin-project/specs-actors/v7/actors/builtin"
	miner7 "github.com/filecoin-project/specs-actors/v7/actors/builtin/miner"
	adt7 "github.com/filecoin-project/specs-actors/v7/actors/util/adt"
	"github.com/ipfs/go-cid"
	"golang.org/x/xerrors"

	"github.com/filecoin-project/lotus/chain/actors"
	"github.com/filecoin-project/lotus/chain/actors/adt"
	"github.com/filecoin-project/lotus/chain/actors/builtin/system"
)

func IsStoragePowerActor(c cid.Cid) bool {
	if name, _, ok := actors.GetActorMetaByCode(c); ok {
		if name != manifest.PowerKey {
			return false
		}
		return true
	}

	if c == builtin0.StoragePowerActorCodeID {
		return true
	}
	if c == builtin2.StoragePowerActorCodeID {
		return true
	}
	if c == builtin3.StoragePowerActorCodeID {
		return true
	}
	if c == builtin4.StoragePowerActorCodeID {
		return true
	}
	if c == builtin5.StoragePowerActorCodeID {
		return true
	}
	if c == builtin6.StoragePowerActorCodeID {
		return true
	}
	if c == builtin7.StoragePowerActorCodeID {
		return true
	}

	return false
}

func IsRewardActor(c cid.Cid) bool {
	if name, _, ok := actors.GetActorMetaByCode(c); ok {
		if name != manifest.RewardKey {
			return false
		}
		return true
	}

	if c == builtin0.RewardActorCodeID {
		return true
	}
	if c == builtin2.RewardActorCodeID {
		return true
	}
	if c == builtin3.RewardActorCodeID {
		return true
	}
	if c == builtin4.RewardActorCodeID {
		return true
	}
	if c == builtin5.RewardActorCodeID {
		return true
	}
	if c == builtin6.RewardActorCodeID {
		return true
	}
	if c == builtin7.RewardActorCodeID {
		return true
	}

	return false
}

func IsInitActor(c cid.Cid) bool {
	if name, _, ok := actors.GetActorMetaByCode(c); ok {
		if name != manifest.InitKey {
			return false
		}
		return true
	}

	if c == builtin0.InitActorCodeID {
		return true
	}
	if c == builtin2.InitActorCodeID {
		return true
	}
	if c == builtin3.InitActorCodeID {
		return true
	}
	if c == builtin4.InitActorCodeID {
		return true
	}
	if c == builtin5.InitActorCodeID {
		return true
	}
	if c == builtin6.InitActorCodeID {
		return true
	}
	if c == builtin7.InitActorCodeID {
		return true
	}

	return false
}

func IsStorageMarketActor(c cid.Cid) bool {
	if name, _, ok := actors.GetActorMetaByCode(c); ok {
		if name != manifest.MarketKey {
			return false
		}
		return true
	}

	if c == builtin0.StorageMarketActorCodeID {
		return true
	}
	if c == builtin2.StorageMarketActorCodeID {
		return true
	}
	if c == builtin3.StorageMarketActorCodeID {
		return true
	}
	if c == builtin4.StorageMarketActorCodeID {
		return true
	}
	if c == builtin5.StorageMarketActorCodeID {
		return true
	}
	if c == builtin6.StorageMarketActorCodeID {
		return true
	}
	if c == builtin7.StorageMarketActorCodeID {
		return true
	}

	return false
}

func IsVerifiedRegistryActor(c cid.Cid) bool {
	if name, _, ok := actors.GetActorMetaByCode(c); ok {
		if name != manifest.VerifregKey {
			return false
		}
		return true
	}

	if c == builtin0.VerifiedRegistryActorCodeID {
		return true
	}
	if c == builtin2.VerifiedRegistryActorCodeID {
		return true
	}
	if c == builtin3.VerifiedRegistryActorCodeID {
		return true
	}
	if c == builtin4.VerifiedRegistryActorCodeID {
		return true
	}
	if c == builtin5.VerifiedRegistryActorCodeID {
		return true
	}
	if c == builtin6.VerifiedRegistryActorCodeID {
		return true
	}
	if c == builtin7.VerifiedRegistryActorCodeID {
		return true
	}

	return false
}

func IsSystemActor(c cid.Cid) bool {
	if name, _, ok := actors.GetActorMetaByCode(c); ok {
		if name != manifest.SystemKey {
			return false
		}
		return true
	}

	if c == builtin0.SystemActorCodeID {
		return true
	}
	if c == builtin2.SystemActorCodeID {
		return true
	}
	if c == builtin3.SystemActorCodeID {
		return true
	}
	if c == builtin4.SystemActorCodeID {
		return true
	}
	if c == builtin5.SystemActorCodeID {
		return true
	}
	if c == builtin6.SystemActorCodeID {
		return true
	}
	if c == builtin7.SystemActorCodeID {
		return true
	}

	return false
}

func IsBurntFundsActor(addr address.Address) bool {
	if addr == builtin.BurntFundsActorAddr {
		return true
	}

	return false
}

func IsDataCapActor(addr address.Address) bool {
	return addr == builtin.DatacapActorAddr
}

func IsCronActor(addr address.Address) bool {
	return addr == builtin.CronActorAddr
}

func IsEamActor(addr address.Address) bool {
	return addr == builtin.EthereumAddressManagerActorAddr
}

func MakeSystemState(store adt.Store, c cid.Cid) (system.State, error) {
	if name, av, ok := actors.GetActorMetaByCode(c); ok {
		if name != manifest.SystemKey {
			return nil, fmt.Errorf("actor code is not system: %s", name)
		}

		switch av {
		case actorstypes.Version8:
			return system.MakeState(store, actorstypes.Version8, cid.Undef)
		case actorstypes.Version9:
			return system.MakeState(store, actorstypes.Version9, cid.Undef)
		case actorstypes.Version10:
			return system.MakeState(store, actorstypes.Version10, cid.Undef)
		case actorstypes.Version11:
			return system.MakeState(store, actorstypes.Version11, cid.Undef)
		case actorstypes.Version12:
			return system.MakeState(store, actorstypes.Version12, cid.Undef)
		case actorstypes.Version13:
			return system.MakeState(store, actorstypes.Version13, cid.Undef)
		case actorstypes.Version14:
			return system.MakeState(store, actorstypes.Version14, cid.Undef)
		case actorstypes.Version15:
			return system.MakeState(store, actorstypes.Version15, cid.Undef)
		}
	}

	if c == builtin0.SystemActorCodeID {
		return system.MakeState(store, actorstypes.Version0, cid.Undef)
	}
	if c == builtin2.SystemActorCodeID {
		return system.MakeState(store, actorstypes.Version2, cid.Undef)
	}
	if c == builtin3.SystemActorCodeID {
		return system.MakeState(store, actorstypes.Version3, cid.Undef)
	}
	if c == builtin4.SystemActorCodeID {
		return system.MakeState(store, actorstypes.Version4, cid.Undef)
	}
	if c == builtin5.SystemActorCodeID {
		return system.MakeState(store, actorstypes.Version5, cid.Undef)
	}
	if c == builtin6.SystemActorCodeID {
		return system.MakeState(store, actorstypes.Version6, cid.Undef)
	}
	if c == builtin7.SystemActorCodeID {
		return system.MakeState(store, actorstypes.Version7, cid.Undef)
	}

	return nil, fmt.Errorf("not system actor code: %v", c)
}

func getMinerResByCode(ctx context.Context, mact *types.Actor, stor adt.Store, resData *model.MinerRes) (err error) {
	var (
		sectorCount          = uint64(0)
		faultSectorCount     = uint64(0)
		activeSectorCount    = uint64(0)
		liveSectorCount      = uint64(0)
		recoverSectorCount   = uint64(0)
		terminateSectorCount = uint64(0)
		precommitSectorCount = uint64(0)
	)

	if name, av, ok := actors.GetActorMetaByCode(mact.Code); ok {
		if name != manifest.MinerKey {
			return fmt.Errorf("actor code is not miner: %s", name)
		}

		switch av {
		case actorstypes.Version8:
			state := miner8.State{}
			err = stor.Get(ctx, mact.Head, &state)
			if err != nil {
				return err
			}

			dls, err := state.LoadDeadlines(stor)
			if err != nil {
				return err
			}

			err = dls.ForEach(stor, func(dlIdx uint64, dl *miner8.Deadline) error {
				partitions, err := dl.PartitionsArray(stor)
				if err != nil {
					return err
				}
				var part miner8.Partition
				return partitions.ForEach(&part, func(partIdx int64) error {
					sc, err := part.Sectors.Count()
					if err != nil {
						return err
					}
					sectorCount += sc

					fc, err := part.Faults.Count()
					if err != nil {
						return err
					}
					faultSectorCount += fc

					active, err := part.ActiveSectors()
					if err != nil {
						return err
					}
					ac, err := active.Count()
					if err != nil {
						return err
					}
					activeSectorCount += ac

					live, err := part.LiveSectors()
					if err != nil {
						return err
					}
					lc, err := live.Count()
					if err != nil {
						return err
					}
					liveSectorCount += lc

					rc, err := part.Recoveries.Count()
					if err != nil {
						return err
					}
					recoverSectorCount += rc

					tc, err := part.Terminated.Count()
					if err != nil {
						return err
					}
					terminateSectorCount += tc

					return nil
				})
			})
			if err != nil {
				return err
			}

			precommitted, err := adt8.AsMap(stor, state.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
			if err != nil {
				return err
			}

			var precommit miner8.SectorPreCommitOnChainInfo
			precommitted.ForEach(&precommit, func(string) error { // nolint: errcheck
				precommitSectorCount++
				return nil
			})

			resData.State = state
			resData.SectorCount = sectorCount
			resData.FaultSectorCount = faultSectorCount
			resData.ActiveSectorCount = activeSectorCount
			resData.LiveSectorCount = liveSectorCount
			resData.RecoverSectorCount = recoverSectorCount
			resData.TerminateSectorCount = terminateSectorCount
			resData.PrecommitSectorCount = precommitSectorCount

			return nil
		case actorstypes.Version9:
			state := miner9.State{}
			err = stor.Get(ctx, mact.Head, &state)
			if err != nil {
				return err
			}

			dls, err := state.LoadDeadlines(stor)
			if err != nil {
				return err
			}

			err = dls.ForEach(stor, func(dlIdx uint64, dl *miner9.Deadline) error {
				partitions, err := dl.PartitionsArray(stor)
				if err != nil {
					return err
				}
				var part miner9.Partition
				return partitions.ForEach(&part, func(partIdx int64) error {
					sc, err := part.Sectors.Count()
					if err != nil {
						return err
					}
					sectorCount += sc

					fc, err := part.Faults.Count()
					if err != nil {
						return err
					}
					faultSectorCount += fc

					active, err := part.ActiveSectors()
					if err != nil {
						return err
					}
					ac, err := active.Count()
					if err != nil {
						return err
					}
					activeSectorCount += ac

					live, err := part.LiveSectors()
					if err != nil {
						return err
					}
					lc, err := live.Count()
					if err != nil {
						return err
					}
					liveSectorCount += lc

					rc, err := part.Recoveries.Count()
					if err != nil {
						return err
					}
					recoverSectorCount += rc

					tc, err := part.Terminated.Count()
					if err != nil {
						return err
					}
					terminateSectorCount += tc

					return nil
				})
			})
			if err != nil {
				return err
			}

			precommitted, err := adt9.AsMap(stor, state.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
			if err != nil {
				return err
			}

			var precommit miner9.SectorPreCommitOnChainInfo
			precommitted.ForEach(&precommit, func(string) error { // nolint: errcheck
				precommitSectorCount++
				return nil
			})

			resData.State = state
			resData.SectorCount = sectorCount
			resData.FaultSectorCount = faultSectorCount
			resData.ActiveSectorCount = activeSectorCount
			resData.LiveSectorCount = liveSectorCount
			resData.RecoverSectorCount = recoverSectorCount
			resData.TerminateSectorCount = terminateSectorCount
			resData.PrecommitSectorCount = precommitSectorCount

			return nil
		case actorstypes.Version10:
			state := miner10.State{}
			err = stor.Get(ctx, mact.Head, &state)
			if err != nil {
				return err
			}

			dls, err := state.LoadDeadlines(stor)
			if err != nil {
				return err
			}

			err = dls.ForEach(stor, func(dlIdx uint64, dl *miner10.Deadline) error {
				partitions, err := dl.PartitionsArray(stor)
				if err != nil {
					return err
				}
				var part miner10.Partition
				return partitions.ForEach(&part, func(partIdx int64) error {
					sc, err := part.Sectors.Count()
					if err != nil {
						return err
					}
					sectorCount += sc

					fc, err := part.Faults.Count()
					if err != nil {
						return err
					}
					faultSectorCount += fc

					active, err := part.ActiveSectors()
					if err != nil {
						return err
					}
					ac, err := active.Count()
					if err != nil {
						return err
					}
					activeSectorCount += ac

					live, err := part.LiveSectors()
					if err != nil {
						return err
					}
					lc, err := live.Count()
					if err != nil {
						return err
					}
					liveSectorCount += lc

					rc, err := part.Recoveries.Count()
					if err != nil {
						return err
					}
					recoverSectorCount += rc

					tc, err := part.Terminated.Count()
					if err != nil {
						return err
					}
					terminateSectorCount += tc

					return nil
				})
			})
			if err != nil {
				return err
			}

			precommitted, err := adt10.AsMap(stor, state.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
			if err != nil {
				return err
			}

			var precommit miner10.SectorPreCommitOnChainInfo
			precommitted.ForEach(&precommit, func(string) error { // nolint: errcheck
				precommitSectorCount++
				return nil
			})

			resData.State = state
			resData.SectorCount = sectorCount
			resData.FaultSectorCount = faultSectorCount
			resData.ActiveSectorCount = activeSectorCount
			resData.LiveSectorCount = liveSectorCount
			resData.RecoverSectorCount = recoverSectorCount
			resData.TerminateSectorCount = terminateSectorCount
			resData.PrecommitSectorCount = precommitSectorCount

			return nil
		case actorstypes.Version11:
			state := miner11.State{}
			err = stor.Get(ctx, mact.Head, &state)
			if err != nil {
				return err
			}

			dls, err := state.LoadDeadlines(stor)
			if err != nil {
				return err
			}

			err = dls.ForEach(stor, func(dlIdx uint64, dl *miner11.Deadline) error {
				partitions, err := dl.PartitionsArray(stor)
				if err != nil {
					return err
				}
				var part miner11.Partition
				return partitions.ForEach(&part, func(partIdx int64) error {
					sc, err := part.Sectors.Count()
					if err != nil {
						return err
					}
					sectorCount += sc

					fc, err := part.Faults.Count()
					if err != nil {
						return err
					}
					faultSectorCount += fc

					active, err := part.ActiveSectors()
					if err != nil {
						return err
					}
					ac, err := active.Count()
					if err != nil {
						return err
					}
					activeSectorCount += ac

					live, err := part.LiveSectors()
					if err != nil {
						return err
					}
					lc, err := live.Count()
					if err != nil {
						return err
					}
					liveSectorCount += lc

					rc, err := part.Recoveries.Count()
					if err != nil {
						return err
					}
					recoverSectorCount += rc

					tc, err := part.Terminated.Count()
					if err != nil {
						return err
					}
					terminateSectorCount += tc

					return nil
				})
			})
			if err != nil {
				return err
			}

			precommitted, err := adt11.AsMap(stor, state.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
			if err != nil {
				return err
			}

			var precommit miner11.SectorPreCommitOnChainInfo
			precommitted.ForEach(&precommit, func(string) error { // nolint: errcheck
				precommitSectorCount++
				return nil
			})

			resData.State = state
			resData.SectorCount = sectorCount
			resData.FaultSectorCount = faultSectorCount
			resData.ActiveSectorCount = activeSectorCount
			resData.LiveSectorCount = liveSectorCount
			resData.RecoverSectorCount = recoverSectorCount
			resData.TerminateSectorCount = terminateSectorCount
			resData.PrecommitSectorCount = precommitSectorCount

			return nil
		case actorstypes.Version12:
			state := miner12.State{}
			err = stor.Get(ctx, mact.Head, &state)
			if err != nil {
				return err
			}

			dls, err := state.LoadDeadlines(stor)
			if err != nil {
				return err
			}

			err = dls.ForEach(stor, func(dlIdx uint64, dl *miner12.Deadline) error {
				partitions, err := dl.PartitionsArray(stor)
				if err != nil {
					return err
				}
				var part miner12.Partition
				return partitions.ForEach(&part, func(partIdx int64) error {
					sc, err := part.Sectors.Count()
					if err != nil {
						return err
					}
					sectorCount += sc

					fc, err := part.Faults.Count()
					if err != nil {
						return err
					}
					faultSectorCount += fc

					active, err := part.ActiveSectors()
					if err != nil {
						return err
					}
					ac, err := active.Count()
					if err != nil {
						return err
					}
					activeSectorCount += ac

					live, err := part.LiveSectors()
					if err != nil {
						return err
					}
					lc, err := live.Count()
					if err != nil {
						return err
					}
					liveSectorCount += lc

					rc, err := part.Recoveries.Count()
					if err != nil {
						return err
					}
					recoverSectorCount += rc

					tc, err := part.Terminated.Count()
					if err != nil {
						return err
					}
					terminateSectorCount += tc

					return nil
				})
			})
			if err != nil {
				return err
			}

			precommitted, err := adt12.AsMap(stor, state.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
			if err != nil {
				return err
			}

			var precommit miner12.SectorPreCommitOnChainInfo
			precommitted.ForEach(&precommit, func(string) error { // nolint: errcheck
				precommitSectorCount++
				return nil
			})

			resData.State = state
			resData.SectorCount = sectorCount
			resData.FaultSectorCount = faultSectorCount
			resData.ActiveSectorCount = activeSectorCount
			resData.LiveSectorCount = liveSectorCount
			resData.RecoverSectorCount = recoverSectorCount
			resData.TerminateSectorCount = terminateSectorCount
			resData.PrecommitSectorCount = precommitSectorCount

			return nil
		case actorstypes.Version13:
			state := miner13.State{}
			err = stor.Get(ctx, mact.Head, &state)
			if err != nil {
				return err
			}

			dls, err := state.LoadDeadlines(stor)
			if err != nil {
				return err
			}

			err = dls.ForEach(stor, func(dlIdx uint64, dl *miner13.Deadline) error {
				partitions, err := dl.PartitionsArray(stor)
				if err != nil {
					return err
				}
				var part miner13.Partition
				return partitions.ForEach(&part, func(partIdx int64) error {
					sc, err := part.Sectors.Count()
					if err != nil {
						return err
					}
					sectorCount += sc

					fc, err := part.Faults.Count()
					if err != nil {
						return err
					}
					faultSectorCount += fc

					active, err := part.ActiveSectors()
					if err != nil {
						return err
					}
					ac, err := active.Count()
					if err != nil {
						return err
					}
					activeSectorCount += ac

					live, err := part.LiveSectors()
					if err != nil {
						return err
					}
					lc, err := live.Count()
					if err != nil {
						return err
					}
					liveSectorCount += lc

					rc, err := part.Recoveries.Count()
					if err != nil {
						return err
					}
					recoverSectorCount += rc

					tc, err := part.Terminated.Count()
					if err != nil {
						return err
					}
					terminateSectorCount += tc

					return nil
				})
			})
			if err != nil {
				return err
			}

			precommitted, err := adt13.AsMap(stor, state.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
			if err != nil {
				return err
			}

			var precommit miner13.SectorPreCommitOnChainInfo
			precommitted.ForEach(&precommit, func(string) error { // nolint: errcheck
				precommitSectorCount++
				return nil
			})

			resData.State = state
			resData.SectorCount = sectorCount
			resData.FaultSectorCount = faultSectorCount
			resData.ActiveSectorCount = activeSectorCount
			resData.LiveSectorCount = liveSectorCount
			resData.RecoverSectorCount = recoverSectorCount
			resData.TerminateSectorCount = terminateSectorCount
			resData.PrecommitSectorCount = precommitSectorCount

			return nil
		case actorstypes.Version14:
			state := miner14.State{}
			err = stor.Get(ctx, mact.Head, &state)
			if err != nil {
				return err
			}

			dls, err := state.LoadDeadlines(stor)
			if err != nil {
				return err
			}

			err = dls.ForEach(stor, func(dlIdx uint64, dl *miner14.Deadline) error {
				partitions, err := dl.PartitionsArray(stor)
				if err != nil {
					return err
				}
				var part miner14.Partition
				return partitions.ForEach(&part, func(partIdx int64) error {
					sc, err := part.Sectors.Count()
					if err != nil {
						return err
					}
					sectorCount += sc

					fc, err := part.Faults.Count()
					if err != nil {
						return err
					}
					faultSectorCount += fc

					active, err := part.ActiveSectors()
					if err != nil {
						return err
					}
					ac, err := active.Count()
					if err != nil {
						return err
					}
					activeSectorCount += ac

					live, err := part.LiveSectors()
					if err != nil {
						return err
					}
					lc, err := live.Count()
					if err != nil {
						return err
					}
					liveSectorCount += lc

					rc, err := part.Recoveries.Count()
					if err != nil {
						return err
					}
					recoverSectorCount += rc

					tc, err := part.Terminated.Count()
					if err != nil {
						return err
					}
					terminateSectorCount += tc

					return nil
				})
			})
			if err != nil {
				return err
			}

			precommitted, err := adt14.AsMap(stor, state.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
			if err != nil {
				return err
			}

			var precommit miner14.SectorPreCommitOnChainInfo
			precommitted.ForEach(&precommit, func(string) error { // nolint: errcheck
				precommitSectorCount++
				return nil
			})

			resData.State = state
			resData.SectorCount = sectorCount
			resData.FaultSectorCount = faultSectorCount
			resData.ActiveSectorCount = activeSectorCount
			resData.LiveSectorCount = liveSectorCount
			resData.RecoverSectorCount = recoverSectorCount
			resData.TerminateSectorCount = terminateSectorCount
			resData.PrecommitSectorCount = precommitSectorCount

			return nil
		case actorstypes.Version15:
			state := miner15.State{}
			err = stor.Get(ctx, mact.Head, &state)
			if err != nil {
				return err
			}

			dls, err := state.LoadDeadlines(stor)
			if err != nil {
				return err
			}

			err = dls.ForEach(stor, func(dlIdx uint64, dl *miner15.Deadline) error {
				partitions, err := dl.PartitionsArray(stor)
				if err != nil {
					return err
				}
				var part miner15.Partition
				return partitions.ForEach(&part, func(partIdx int64) error {
					sc, err := part.Sectors.Count()
					if err != nil {
						return err
					}
					sectorCount += sc

					fc, err := part.Faults.Count()
					if err != nil {
						return err
					}
					faultSectorCount += fc

					active, err := part.ActiveSectors()
					if err != nil {
						return err
					}
					ac, err := active.Count()
					if err != nil {
						return err
					}
					activeSectorCount += ac

					live, err := part.LiveSectors()
					if err != nil {
						return err
					}
					lc, err := live.Count()
					if err != nil {
						return err
					}
					liveSectorCount += lc

					rc, err := part.Recoveries.Count()
					if err != nil {
						return err
					}
					recoverSectorCount += rc

					tc, err := part.Terminated.Count()
					if err != nil {
						return err
					}
					terminateSectorCount += tc

					return nil
				})
			})
			if err != nil {
				return err
			}

			precommitted, err := adt15.AsMap(stor, state.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
			if err != nil {
				return err
			}

			var precommit miner15.SectorPreCommitOnChainInfo
			precommitted.ForEach(&precommit, func(string) error { // nolint: errcheck
				precommitSectorCount++
				return nil
			})

			resData.State = state
			resData.SectorCount = sectorCount
			resData.FaultSectorCount = faultSectorCount
			resData.ActiveSectorCount = activeSectorCount
			resData.LiveSectorCount = liveSectorCount
			resData.RecoverSectorCount = recoverSectorCount
			resData.TerminateSectorCount = terminateSectorCount
			resData.PrecommitSectorCount = precommitSectorCount

			return nil

		}
	}

	switch mact.Code {

	case builtin0.StorageMinerActorCodeID:
		state := miner0.State{}
		err = stor.Get(ctx, mact.Head, &state)
		if err != nil {
			return err
		}

		dls, err := state.LoadDeadlines(stor)
		if err != nil {
			return err
		}

		err = dls.ForEach(stor, func(dlIdx uint64, dl *miner0.Deadline) error {
			partitions, err := dl.PartitionsArray(stor)
			if err != nil {
				return err
			}
			var part miner0.Partition
			return partitions.ForEach(&part, func(partIdx int64) error {
				sc, err := part.Sectors.Count()
				if err != nil {
					return err
				}
				sectorCount += sc

				fc, err := part.Faults.Count()
				if err != nil {
					return err
				}
				faultSectorCount += fc

				active, err := part.ActiveSectors()
				if err != nil {
					return err
				}
				ac, err := active.Count()
				if err != nil {
					return err
				}
				activeSectorCount += ac

				live, err := part.LiveSectors()
				if err != nil {
					return err
				}
				lc, err := live.Count()
				if err != nil {
					return err
				}
				liveSectorCount += lc

				rc, err := part.Recoveries.Count()
				if err != nil {
					return err
				}
				recoverSectorCount += rc

				tc, err := part.Terminated.Count()
				if err != nil {
					return err
				}
				terminateSectorCount += tc

				return nil
			})
		})
		if err != nil {
			return err
		}

		precommitted, err := adt0.AsMap(stor, state.PreCommittedSectors)

		if err != nil {
			return err
		}

		var precommit miner0.SectorPreCommitOnChainInfo
		precommitted.ForEach(&precommit, func(string) error { // nolint: errcheck
			precommitSectorCount++
			return nil
		})

		resData.State = state
		resData.SectorCount = sectorCount
		resData.FaultSectorCount = faultSectorCount
		resData.ActiveSectorCount = activeSectorCount
		resData.LiveSectorCount = liveSectorCount
		resData.RecoverSectorCount = recoverSectorCount
		resData.TerminateSectorCount = terminateSectorCount
		resData.PrecommitSectorCount = precommitSectorCount

		return nil

	case builtin2.StorageMinerActorCodeID:
		state := miner2.State{}
		err = stor.Get(ctx, mact.Head, &state)
		if err != nil {
			return err
		}

		dls, err := state.LoadDeadlines(stor)
		if err != nil {
			return err
		}

		err = dls.ForEach(stor, func(dlIdx uint64, dl *miner2.Deadline) error {
			partitions, err := dl.PartitionsArray(stor)
			if err != nil {
				return err
			}
			var part miner2.Partition
			return partitions.ForEach(&part, func(partIdx int64) error {
				sc, err := part.Sectors.Count()
				if err != nil {
					return err
				}
				sectorCount += sc

				fc, err := part.Faults.Count()
				if err != nil {
					return err
				}
				faultSectorCount += fc

				active, err := part.ActiveSectors()
				if err != nil {
					return err
				}
				ac, err := active.Count()
				if err != nil {
					return err
				}
				activeSectorCount += ac

				live, err := part.LiveSectors()
				if err != nil {
					return err
				}
				lc, err := live.Count()
				if err != nil {
					return err
				}
				liveSectorCount += lc

				rc, err := part.Recoveries.Count()
				if err != nil {
					return err
				}
				recoverSectorCount += rc

				tc, err := part.Terminated.Count()
				if err != nil {
					return err
				}
				terminateSectorCount += tc

				return nil
			})
		})
		if err != nil {
			return err
		}

		precommitted, err := adt2.AsMap(stor, state.PreCommittedSectors)

		if err != nil {
			return err
		}

		var precommit miner2.SectorPreCommitOnChainInfo
		precommitted.ForEach(&precommit, func(string) error { // nolint: errcheck
			precommitSectorCount++
			return nil
		})

		resData.State = state
		resData.SectorCount = sectorCount
		resData.FaultSectorCount = faultSectorCount
		resData.ActiveSectorCount = activeSectorCount
		resData.LiveSectorCount = liveSectorCount
		resData.RecoverSectorCount = recoverSectorCount
		resData.TerminateSectorCount = terminateSectorCount
		resData.PrecommitSectorCount = precommitSectorCount

		return nil

	case builtin3.StorageMinerActorCodeID:
		state := miner3.State{}
		err = stor.Get(ctx, mact.Head, &state)
		if err != nil {
			return err
		}

		dls, err := state.LoadDeadlines(stor)
		if err != nil {
			return err
		}

		err = dls.ForEach(stor, func(dlIdx uint64, dl *miner3.Deadline) error {
			partitions, err := dl.PartitionsArray(stor)
			if err != nil {
				return err
			}
			var part miner3.Partition
			return partitions.ForEach(&part, func(partIdx int64) error {
				sc, err := part.Sectors.Count()
				if err != nil {
					return err
				}
				sectorCount += sc

				fc, err := part.Faults.Count()
				if err != nil {
					return err
				}
				faultSectorCount += fc

				active, err := part.ActiveSectors()
				if err != nil {
					return err
				}
				ac, err := active.Count()
				if err != nil {
					return err
				}
				activeSectorCount += ac

				live, err := part.LiveSectors()
				if err != nil {
					return err
				}
				lc, err := live.Count()
				if err != nil {
					return err
				}
				liveSectorCount += lc

				rc, err := part.Recoveries.Count()
				if err != nil {
					return err
				}
				recoverSectorCount += rc

				tc, err := part.Terminated.Count()
				if err != nil {
					return err
				}
				terminateSectorCount += tc

				return nil
			})
		})
		if err != nil {
			return err
		}

		precommitted, err := adt3.AsMap(stor, state.PreCommittedSectors, builtin3.DefaultHamtBitwidth)

		if err != nil {
			return err
		}

		var precommit miner3.SectorPreCommitOnChainInfo
		precommitted.ForEach(&precommit, func(string) error { // nolint: errcheck
			precommitSectorCount++
			return nil
		})

		resData.State = state
		resData.SectorCount = sectorCount
		resData.FaultSectorCount = faultSectorCount
		resData.ActiveSectorCount = activeSectorCount
		resData.LiveSectorCount = liveSectorCount
		resData.RecoverSectorCount = recoverSectorCount
		resData.TerminateSectorCount = terminateSectorCount
		resData.PrecommitSectorCount = precommitSectorCount

		return nil

	case builtin4.StorageMinerActorCodeID:
		state := miner4.State{}
		err = stor.Get(ctx, mact.Head, &state)
		if err != nil {
			return err
		}

		dls, err := state.LoadDeadlines(stor)
		if err != nil {
			return err
		}

		err = dls.ForEach(stor, func(dlIdx uint64, dl *miner4.Deadline) error {
			partitions, err := dl.PartitionsArray(stor)
			if err != nil {
				return err
			}
			var part miner4.Partition
			return partitions.ForEach(&part, func(partIdx int64) error {
				sc, err := part.Sectors.Count()
				if err != nil {
					return err
				}
				sectorCount += sc

				fc, err := part.Faults.Count()
				if err != nil {
					return err
				}
				faultSectorCount += fc

				active, err := part.ActiveSectors()
				if err != nil {
					return err
				}
				ac, err := active.Count()
				if err != nil {
					return err
				}
				activeSectorCount += ac

				live, err := part.LiveSectors()
				if err != nil {
					return err
				}
				lc, err := live.Count()
				if err != nil {
					return err
				}
				liveSectorCount += lc

				rc, err := part.Recoveries.Count()
				if err != nil {
					return err
				}
				recoverSectorCount += rc

				tc, err := part.Terminated.Count()
				if err != nil {
					return err
				}
				terminateSectorCount += tc

				return nil
			})
		})
		if err != nil {
			return err
		}

		precommitted, err := adt4.AsMap(stor, state.PreCommittedSectors, builtin4.DefaultHamtBitwidth)

		if err != nil {
			return err
		}

		var precommit miner4.SectorPreCommitOnChainInfo
		precommitted.ForEach(&precommit, func(string) error { // nolint: errcheck
			precommitSectorCount++
			return nil
		})

		resData.State = state
		resData.SectorCount = sectorCount
		resData.FaultSectorCount = faultSectorCount
		resData.ActiveSectorCount = activeSectorCount
		resData.LiveSectorCount = liveSectorCount
		resData.RecoverSectorCount = recoverSectorCount
		resData.TerminateSectorCount = terminateSectorCount
		resData.PrecommitSectorCount = precommitSectorCount

		return nil

	case builtin5.StorageMinerActorCodeID:
		state := miner5.State{}
		err = stor.Get(ctx, mact.Head, &state)
		if err != nil {
			return err
		}

		dls, err := state.LoadDeadlines(stor)
		if err != nil {
			return err
		}

		err = dls.ForEach(stor, func(dlIdx uint64, dl *miner5.Deadline) error {
			partitions, err := dl.PartitionsArray(stor)
			if err != nil {
				return err
			}
			var part miner5.Partition
			return partitions.ForEach(&part, func(partIdx int64) error {
				sc, err := part.Sectors.Count()
				if err != nil {
					return err
				}
				sectorCount += sc

				fc, err := part.Faults.Count()
				if err != nil {
					return err
				}
				faultSectorCount += fc

				active, err := part.ActiveSectors()
				if err != nil {
					return err
				}
				ac, err := active.Count()
				if err != nil {
					return err
				}
				activeSectorCount += ac

				live, err := part.LiveSectors()
				if err != nil {
					return err
				}
				lc, err := live.Count()
				if err != nil {
					return err
				}
				liveSectorCount += lc

				rc, err := part.Recoveries.Count()
				if err != nil {
					return err
				}
				recoverSectorCount += rc

				tc, err := part.Terminated.Count()
				if err != nil {
					return err
				}
				terminateSectorCount += tc

				return nil
			})
		})
		if err != nil {
			return err
		}

		precommitted, err := adt5.AsMap(stor, state.PreCommittedSectors, builtin5.DefaultHamtBitwidth)

		if err != nil {
			return err
		}

		var precommit miner5.SectorPreCommitOnChainInfo
		precommitted.ForEach(&precommit, func(string) error { // nolint: errcheck
			precommitSectorCount++
			return nil
		})

		resData.State = state
		resData.SectorCount = sectorCount
		resData.FaultSectorCount = faultSectorCount
		resData.ActiveSectorCount = activeSectorCount
		resData.LiveSectorCount = liveSectorCount
		resData.RecoverSectorCount = recoverSectorCount
		resData.TerminateSectorCount = terminateSectorCount
		resData.PrecommitSectorCount = precommitSectorCount

		return nil

	case builtin6.StorageMinerActorCodeID:
		state := miner6.State{}
		err = stor.Get(ctx, mact.Head, &state)
		if err != nil {
			return err
		}

		dls, err := state.LoadDeadlines(stor)
		if err != nil {
			return err
		}

		err = dls.ForEach(stor, func(dlIdx uint64, dl *miner6.Deadline) error {
			partitions, err := dl.PartitionsArray(stor)
			if err != nil {
				return err
			}
			var part miner6.Partition
			return partitions.ForEach(&part, func(partIdx int64) error {
				sc, err := part.Sectors.Count()
				if err != nil {
					return err
				}
				sectorCount += sc

				fc, err := part.Faults.Count()
				if err != nil {
					return err
				}
				faultSectorCount += fc

				active, err := part.ActiveSectors()
				if err != nil {
					return err
				}
				ac, err := active.Count()
				if err != nil {
					return err
				}
				activeSectorCount += ac

				live, err := part.LiveSectors()
				if err != nil {
					return err
				}
				lc, err := live.Count()
				if err != nil {
					return err
				}
				liveSectorCount += lc

				rc, err := part.Recoveries.Count()
				if err != nil {
					return err
				}
				recoverSectorCount += rc

				tc, err := part.Terminated.Count()
				if err != nil {
					return err
				}
				terminateSectorCount += tc

				return nil
			})
		})
		if err != nil {
			return err
		}

		precommitted, err := adt6.AsMap(stor, state.PreCommittedSectors, builtin6.DefaultHamtBitwidth)

		if err != nil {
			return err
		}

		var precommit miner6.SectorPreCommitOnChainInfo
		precommitted.ForEach(&precommit, func(string) error { // nolint: errcheck
			precommitSectorCount++
			return nil
		})

		resData.State = state
		resData.SectorCount = sectorCount
		resData.FaultSectorCount = faultSectorCount
		resData.ActiveSectorCount = activeSectorCount
		resData.LiveSectorCount = liveSectorCount
		resData.RecoverSectorCount = recoverSectorCount
		resData.TerminateSectorCount = terminateSectorCount
		resData.PrecommitSectorCount = precommitSectorCount

		return nil

	case builtin7.StorageMinerActorCodeID:
		state := miner7.State{}
		err = stor.Get(ctx, mact.Head, &state)
		if err != nil {
			return err
		}

		dls, err := state.LoadDeadlines(stor)
		if err != nil {
			return err
		}

		err = dls.ForEach(stor, func(dlIdx uint64, dl *miner7.Deadline) error {
			partitions, err := dl.PartitionsArray(stor)
			if err != nil {
				return err
			}
			var part miner7.Partition
			return partitions.ForEach(&part, func(partIdx int64) error {
				sc, err := part.Sectors.Count()
				if err != nil {
					return err
				}
				sectorCount += sc

				fc, err := part.Faults.Count()
				if err != nil {
					return err
				}
				faultSectorCount += fc

				active, err := part.ActiveSectors()
				if err != nil {
					return err
				}
				ac, err := active.Count()
				if err != nil {
					return err
				}
				activeSectorCount += ac

				live, err := part.LiveSectors()
				if err != nil {
					return err
				}
				lc, err := live.Count()
				if err != nil {
					return err
				}
				liveSectorCount += lc

				rc, err := part.Recoveries.Count()
				if err != nil {
					return err
				}
				recoverSectorCount += rc

				tc, err := part.Terminated.Count()
				if err != nil {
					return err
				}
				terminateSectorCount += tc

				return nil
			})
		})
		if err != nil {
			return err
		}

		precommitted, err := adt7.AsMap(stor, state.PreCommittedSectors, builtin7.DefaultHamtBitwidth)

		if err != nil {
			return err
		}

		var precommit miner7.SectorPreCommitOnChainInfo
		precommitted.ForEach(&precommit, func(string) error { // nolint: errcheck
			precommitSectorCount++
			return nil
		})

		resData.State = state
		resData.SectorCount = sectorCount
		resData.FaultSectorCount = faultSectorCount
		resData.ActiveSectorCount = activeSectorCount
		resData.LiveSectorCount = liveSectorCount
		resData.RecoverSectorCount = recoverSectorCount
		resData.TerminateSectorCount = terminateSectorCount
		resData.PrecommitSectorCount = precommitSectorCount

		return nil

	}

	return fmt.Errorf("unknown actor code %s", mact.Code)
}

func getDepositToBurnByCode(ctx context.Context, mact *types.Actor, stor adt.Store, curEpoch abi.ChainEpoch) (abi.TokenAmount, error) {
	version := 0
	if name, av, ok := actors.GetActorMetaByCode(mact.Code); ok {
		if name != manifest.MinerKey {
			return abi.NewTokenAmount(0), fmt.Errorf("actor code is not miner: %s", name)
		}

		switch av {

		case actorstypes.Version8:
			state := &miner8.State{}
			err := stor.Get(ctx, mact.Head, state)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}

			if !state.PreCommittedSectorsCleanUp.Defined() {
				return abi.NewTokenAmount(0), nil
			}
			depositToBurn, err := CleanUpExpiredPreCommits(state, stor, curEpoch)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}
			return depositToBurn, nil

		case actorstypes.Version9:
			state := &miner9.State{}
			err := stor.Get(ctx, mact.Head, state)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}

			if !state.PreCommittedSectorsCleanUp.Defined() {
				return abi.NewTokenAmount(0), nil
			}
			depositToBurn, err := CleanUpExpiredPreCommits(state, stor, curEpoch)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}
			return depositToBurn, nil

		case actorstypes.Version10:
			state := &miner10.State{}
			err := stor.Get(ctx, mact.Head, state)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}

			if !state.PreCommittedSectorsCleanUp.Defined() {
				return abi.NewTokenAmount(0), nil
			}
			depositToBurn, err := CleanUpExpiredPreCommits(state, stor, curEpoch)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}
			return depositToBurn, nil

		case actorstypes.Version11:
			state := &miner11.State{}
			err := stor.Get(ctx, mact.Head, state)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}

			if !state.PreCommittedSectorsCleanUp.Defined() {
				return abi.NewTokenAmount(0), nil
			}
			depositToBurn, err := CleanUpExpiredPreCommits(state, stor, curEpoch)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}
			return depositToBurn, nil

		case actorstypes.Version12:
			state := &miner12.State{}
			err := stor.Get(ctx, mact.Head, state)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}

			if !state.PreCommittedSectorsCleanUp.Defined() {
				return abi.NewTokenAmount(0), nil
			}
			depositToBurn, err := CleanUpExpiredPreCommits(state, stor, curEpoch)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}
			return depositToBurn, nil

		case actorstypes.Version13:
			state := &miner13.State{}
			err := stor.Get(ctx, mact.Head, state)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}

			if !state.PreCommittedSectorsCleanUp.Defined() {
				return abi.NewTokenAmount(0), nil
			}
			depositToBurn, err := CleanUpExpiredPreCommits(state, stor, curEpoch)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}
			return depositToBurn, nil

		case actorstypes.Version14:
			state := &miner14.State{}
			err := stor.Get(ctx, mact.Head, state)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}

			if !state.PreCommittedSectorsCleanUp.Defined() {
				return abi.NewTokenAmount(0), nil
			}
			depositToBurn, err := CleanUpExpiredPreCommits(state, stor, curEpoch)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}
			return depositToBurn, nil

		case actorstypes.Version15:
			state := &miner15.State{}
			err := stor.Get(ctx, mact.Head, state)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}

			if !state.PreCommittedSectorsCleanUp.Defined() {
				return abi.NewTokenAmount(0), nil
			}
			depositToBurn, err := CleanUpExpiredPreCommits(state, stor, curEpoch)
			if err != nil {
				return abi.NewTokenAmount(0), err
			}
			return depositToBurn, nil

		}
	}

	switch mact.Code {

	case builtin0.StorageMinerActorCodeID:
		return abi.NewTokenAmount(0), fmt.Errorf("no PreCommittedSectorsCleanUp in state%v", version)

	case builtin2.StorageMinerActorCodeID:
		return abi.NewTokenAmount(0), fmt.Errorf("no PreCommittedSectorsCleanUp in state%v", version)

	case builtin3.StorageMinerActorCodeID:
		return abi.NewTokenAmount(0), fmt.Errorf("no PreCommittedSectorsCleanUp in state%v", version)

	case builtin4.StorageMinerActorCodeID:
		return abi.NewTokenAmount(0), fmt.Errorf("no PreCommittedSectorsCleanUp in state%v", version)

	case builtin5.StorageMinerActorCodeID:
		state := miner5.State{}
		err := stor.Get(ctx, mact.Head, &state)
		if err != nil {
			return abi.NewTokenAmount(0), err
		}

		if !state.PreCommittedSectorsCleanUp.Defined() {
			return abi.NewTokenAmount(0), nil
		}
		depositToBurn, err := state.CleanUpExpiredPreCommits(stor, curEpoch)
		if err != nil {
			return abi.NewTokenAmount(0), err
		}
		return depositToBurn, nil

	case builtin6.StorageMinerActorCodeID:
		state := miner6.State{}
		err := stor.Get(ctx, mact.Head, &state)
		if err != nil {
			return abi.NewTokenAmount(0), err
		}

		if !state.PreCommittedSectorsCleanUp.Defined() {
			return abi.NewTokenAmount(0), nil
		}
		depositToBurn, err := state.CleanUpExpiredPreCommits(stor, curEpoch)
		if err != nil {
			return abi.NewTokenAmount(0), err
		}
		return depositToBurn, nil

	case builtin7.StorageMinerActorCodeID:
		state := miner7.State{}
		err := stor.Get(ctx, mact.Head, &state)
		if err != nil {
			return abi.NewTokenAmount(0), err
		}

		if !state.PreCommittedSectorsCleanUp.Defined() {
			return abi.NewTokenAmount(0), nil
		}
		depositToBurn, err := state.CleanUpExpiredPreCommits(stor, curEpoch)
		if err != nil {
			return abi.NewTokenAmount(0), err
		}
		return depositToBurn, nil

	}

	return abi.NewTokenAmount(0), fmt.Errorf("unknown actor code %s", mact.Code)
}

func CleanUpExpiredPreCommits(state interface{}, store adt.Store, currEpoch abi.ChainEpoch) (depositToBurn abi.TokenAmount, err error) {
	switch state.(type) {
	case *miner8.State:
		st := state.(*miner8.State)
		depositToBurn = abi.NewTokenAmount(0)

		// cleanup expired pre-committed sectors
		cleanUpQ, err := util8.LoadBitfieldQueue(store, st.PreCommittedSectorsCleanUp, st.QuantSpecEveryDeadline(), miner8.PrecommitCleanUpAmtBitwidth)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to load sector expiry queue: %w", err)
		}

		sectors, modified, err := PopUntil(cleanUpQ, currEpoch)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to pop expired sectors: %w", err)
		}

		if modified {
			st.PreCommittedSectorsCleanUp, err = cleanUpQ.Root()
			if err != nil {
				return depositToBurn, xerrors.Errorf("failed to save pre commit clean up queue: %w", err)
			}
		}

		var precommitsToDelete []abi.SectorNumber
		if err = sectors.ForEach(func(i uint64) error {
			sectorNo := abi.SectorNumber(i)
			sector, found, err := st.GetPrecommittedSector(store, sectorNo)
			if err != nil {
				return err
			}
			if !found {
				// already committed/deleted
				return nil
			}

			// mark it for deletion
			precommitsToDelete = append(precommitsToDelete, sectorNo)

			// increment deposit to burn
			depositToBurn = big.Add(depositToBurn, sector.PreCommitDeposit)
			return nil
		}); err != nil {
			return big.Zero(), xerrors.Errorf("failed to check pre-commit expiries: %w", err)
		}

		// Actually delete it.
		if len(precommitsToDelete) > 0 {
			if err := DeletePrecommittedSectors(st, store, precommitsToDelete...); err != nil {
				return big.Zero(), fmt.Errorf("failed to delete pre-commits: %w", err)
			}
		}

		st.PreCommitDeposits = big.Sub(st.PreCommitDeposits, depositToBurn)
		if st.PreCommitDeposits.LessThan(big.Zero()) {
			return big.Zero(), xerrors.Errorf("pre-commit clean up caused negative deposits: %v", st.PreCommitDeposits)
		}

		// This deposit was locked separately to pledge collateral so there's no pledge change here.
		return depositToBurn, nil

	case *miner9.State:
		st := state.(*miner9.State)
		depositToBurn = abi.NewTokenAmount(0)

		// cleanup expired pre-committed sectors
		cleanUpQ, err := util9.LoadBitfieldQueue(store, st.PreCommittedSectorsCleanUp, st.QuantSpecEveryDeadline(), miner9.PrecommitCleanUpAmtBitwidth)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to load sector expiry queue: %w", err)
		}

		sectors, modified, err := PopUntil(cleanUpQ, currEpoch)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to pop expired sectors: %w", err)
		}

		if modified {
			st.PreCommittedSectorsCleanUp, err = cleanUpQ.Root()
			if err != nil {
				return depositToBurn, xerrors.Errorf("failed to save pre commit clean up queue: %w", err)
			}
		}

		var precommitsToDelete []abi.SectorNumber
		if err = sectors.ForEach(func(i uint64) error {
			sectorNo := abi.SectorNumber(i)
			sector, found, err := st.GetPrecommittedSector(store, sectorNo)
			if err != nil {
				return err
			}
			if !found {
				// already committed/deleted
				return nil
			}

			// mark it for deletion
			precommitsToDelete = append(precommitsToDelete, sectorNo)

			// increment deposit to burn
			depositToBurn = big.Add(depositToBurn, sector.PreCommitDeposit)
			return nil
		}); err != nil {
			return big.Zero(), xerrors.Errorf("failed to check pre-commit expiries: %w", err)
		}

		// Actually delete it.
		if len(precommitsToDelete) > 0 {
			if err := DeletePrecommittedSectors(st, store, precommitsToDelete...); err != nil {
				return big.Zero(), fmt.Errorf("failed to delete pre-commits: %w", err)
			}
		}

		st.PreCommitDeposits = big.Sub(st.PreCommitDeposits, depositToBurn)
		if st.PreCommitDeposits.LessThan(big.Zero()) {
			return big.Zero(), xerrors.Errorf("pre-commit clean up caused negative deposits: %v", st.PreCommitDeposits)
		}

		// This deposit was locked separately to pledge collateral so there's no pledge change here.
		return depositToBurn, nil

	case *miner10.State:
		st := state.(*miner10.State)
		depositToBurn = abi.NewTokenAmount(0)

		// cleanup expired pre-committed sectors
		cleanUpQ, err := util10.LoadBitfieldQueue(store, st.PreCommittedSectorsCleanUp, st.QuantSpecEveryDeadline(), miner10.PrecommitCleanUpAmtBitwidth)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to load sector expiry queue: %w", err)
		}

		sectors, modified, err := PopUntil(cleanUpQ, currEpoch)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to pop expired sectors: %w", err)
		}

		if modified {
			st.PreCommittedSectorsCleanUp, err = cleanUpQ.Root()
			if err != nil {
				return depositToBurn, xerrors.Errorf("failed to save pre commit clean up queue: %w", err)
			}
		}

		var precommitsToDelete []abi.SectorNumber
		if err = sectors.ForEach(func(i uint64) error {
			sectorNo := abi.SectorNumber(i)
			sector, found, err := st.GetPrecommittedSector(store, sectorNo)
			if err != nil {
				return err
			}
			if !found {
				// already committed/deleted
				return nil
			}

			// mark it for deletion
			precommitsToDelete = append(precommitsToDelete, sectorNo)

			// increment deposit to burn
			depositToBurn = big.Add(depositToBurn, sector.PreCommitDeposit)
			return nil
		}); err != nil {
			return big.Zero(), xerrors.Errorf("failed to check pre-commit expiries: %w", err)
		}

		// Actually delete it.
		if len(precommitsToDelete) > 0 {
			if err := DeletePrecommittedSectors(st, store, precommitsToDelete...); err != nil {
				return big.Zero(), fmt.Errorf("failed to delete pre-commits: %w", err)
			}
		}

		st.PreCommitDeposits = big.Sub(st.PreCommitDeposits, depositToBurn)
		if st.PreCommitDeposits.LessThan(big.Zero()) {
			return big.Zero(), xerrors.Errorf("pre-commit clean up caused negative deposits: %v", st.PreCommitDeposits)
		}

		// This deposit was locked separately to pledge collateral so there's no pledge change here.
		return depositToBurn, nil

	case *miner11.State:
		st := state.(*miner11.State)
		depositToBurn = abi.NewTokenAmount(0)

		// cleanup expired pre-committed sectors
		cleanUpQ, err := util11.LoadBitfieldQueue(store, st.PreCommittedSectorsCleanUp, st.QuantSpecEveryDeadline(), miner11.PrecommitCleanUpAmtBitwidth)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to load sector expiry queue: %w", err)
		}

		sectors, modified, err := PopUntil(cleanUpQ, currEpoch)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to pop expired sectors: %w", err)
		}

		if modified {
			st.PreCommittedSectorsCleanUp, err = cleanUpQ.Root()
			if err != nil {
				return depositToBurn, xerrors.Errorf("failed to save pre commit clean up queue: %w", err)
			}
		}

		var precommitsToDelete []abi.SectorNumber
		if err = sectors.ForEach(func(i uint64) error {
			sectorNo := abi.SectorNumber(i)
			sector, found, err := st.GetPrecommittedSector(store, sectorNo)
			if err != nil {
				return err
			}
			if !found {
				// already committed/deleted
				return nil
			}

			// mark it for deletion
			precommitsToDelete = append(precommitsToDelete, sectorNo)

			// increment deposit to burn
			depositToBurn = big.Add(depositToBurn, sector.PreCommitDeposit)
			return nil
		}); err != nil {
			return big.Zero(), xerrors.Errorf("failed to check pre-commit expiries: %w", err)
		}

		// Actually delete it.
		if len(precommitsToDelete) > 0 {
			if err := DeletePrecommittedSectors(st, store, precommitsToDelete...); err != nil {
				return big.Zero(), fmt.Errorf("failed to delete pre-commits: %w", err)
			}
		}

		st.PreCommitDeposits = big.Sub(st.PreCommitDeposits, depositToBurn)
		if st.PreCommitDeposits.LessThan(big.Zero()) {
			return big.Zero(), xerrors.Errorf("pre-commit clean up caused negative deposits: %v", st.PreCommitDeposits)
		}

		// This deposit was locked separately to pledge collateral so there's no pledge change here.
		return depositToBurn, nil

	case *miner12.State:
		st := state.(*miner12.State)
		depositToBurn = abi.NewTokenAmount(0)

		// cleanup expired pre-committed sectors
		cleanUpQ, err := util12.LoadBitfieldQueue(store, st.PreCommittedSectorsCleanUp, st.QuantSpecEveryDeadline(), miner12.PrecommitCleanUpAmtBitwidth)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to load sector expiry queue: %w", err)
		}

		sectors, modified, err := PopUntil(cleanUpQ, currEpoch)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to pop expired sectors: %w", err)
		}

		if modified {
			st.PreCommittedSectorsCleanUp, err = cleanUpQ.Root()
			if err != nil {
				return depositToBurn, xerrors.Errorf("failed to save pre commit clean up queue: %w", err)
			}
		}

		var precommitsToDelete []abi.SectorNumber
		if err = sectors.ForEach(func(i uint64) error {
			sectorNo := abi.SectorNumber(i)
			sector, found, err := st.GetPrecommittedSector(store, sectorNo)
			if err != nil {
				return err
			}
			if !found {
				// already committed/deleted
				return nil
			}

			// mark it for deletion
			precommitsToDelete = append(precommitsToDelete, sectorNo)

			// increment deposit to burn
			depositToBurn = big.Add(depositToBurn, sector.PreCommitDeposit)
			return nil
		}); err != nil {
			return big.Zero(), xerrors.Errorf("failed to check pre-commit expiries: %w", err)
		}

		// Actually delete it.
		if len(precommitsToDelete) > 0 {
			if err := DeletePrecommittedSectors(st, store, precommitsToDelete...); err != nil {
				return big.Zero(), fmt.Errorf("failed to delete pre-commits: %w", err)
			}
		}

		st.PreCommitDeposits = big.Sub(st.PreCommitDeposits, depositToBurn)
		if st.PreCommitDeposits.LessThan(big.Zero()) {
			return big.Zero(), xerrors.Errorf("pre-commit clean up caused negative deposits: %v", st.PreCommitDeposits)
		}

		// This deposit was locked separately to pledge collateral so there's no pledge change here.
		return depositToBurn, nil

	case *miner13.State:
		st := state.(*miner13.State)
		depositToBurn = abi.NewTokenAmount(0)

		// cleanup expired pre-committed sectors
		cleanUpQ, err := util13.LoadBitfieldQueue(store, st.PreCommittedSectorsCleanUp, st.QuantSpecEveryDeadline(), miner13.PrecommitCleanUpAmtBitwidth)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to load sector expiry queue: %w", err)
		}

		sectors, modified, err := PopUntil(cleanUpQ, currEpoch)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to pop expired sectors: %w", err)
		}

		if modified {
			st.PreCommittedSectorsCleanUp, err = cleanUpQ.Root()
			if err != nil {
				return depositToBurn, xerrors.Errorf("failed to save pre commit clean up queue: %w", err)
			}
		}

		var precommitsToDelete []abi.SectorNumber
		if err = sectors.ForEach(func(i uint64) error {
			sectorNo := abi.SectorNumber(i)
			sector, found, err := st.GetPrecommittedSector(store, sectorNo)
			if err != nil {
				return err
			}
			if !found {
				// already committed/deleted
				return nil
			}

			// mark it for deletion
			precommitsToDelete = append(precommitsToDelete, sectorNo)

			// increment deposit to burn
			depositToBurn = big.Add(depositToBurn, sector.PreCommitDeposit)
			return nil
		}); err != nil {
			return big.Zero(), xerrors.Errorf("failed to check pre-commit expiries: %w", err)
		}

		// Actually delete it.
		if len(precommitsToDelete) > 0 {
			if err := DeletePrecommittedSectors(st, store, precommitsToDelete...); err != nil {
				return big.Zero(), fmt.Errorf("failed to delete pre-commits: %w", err)
			}
		}

		st.PreCommitDeposits = big.Sub(st.PreCommitDeposits, depositToBurn)
		if st.PreCommitDeposits.LessThan(big.Zero()) {
			return big.Zero(), xerrors.Errorf("pre-commit clean up caused negative deposits: %v", st.PreCommitDeposits)
		}

		// This deposit was locked separately to pledge collateral so there's no pledge change here.
		return depositToBurn, nil

	case *miner14.State:
		st := state.(*miner14.State)
		depositToBurn = abi.NewTokenAmount(0)

		// cleanup expired pre-committed sectors
		cleanUpQ, err := util14.LoadBitfieldQueue(store, st.PreCommittedSectorsCleanUp, st.QuantSpecEveryDeadline(), miner14.PrecommitCleanUpAmtBitwidth)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to load sector expiry queue: %w", err)
		}

		sectors, modified, err := PopUntil(cleanUpQ, currEpoch)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to pop expired sectors: %w", err)
		}

		if modified {
			st.PreCommittedSectorsCleanUp, err = cleanUpQ.Root()
			if err != nil {
				return depositToBurn, xerrors.Errorf("failed to save pre commit clean up queue: %w", err)
			}
		}

		var precommitsToDelete []abi.SectorNumber
		if err = sectors.ForEach(func(i uint64) error {
			sectorNo := abi.SectorNumber(i)
			sector, found, err := st.GetPrecommittedSector(store, sectorNo)
			if err != nil {
				return err
			}
			if !found {
				// already committed/deleted
				return nil
			}

			// mark it for deletion
			precommitsToDelete = append(precommitsToDelete, sectorNo)

			// increment deposit to burn
			depositToBurn = big.Add(depositToBurn, sector.PreCommitDeposit)
			return nil
		}); err != nil {
			return big.Zero(), xerrors.Errorf("failed to check pre-commit expiries: %w", err)
		}

		// Actually delete it.
		if len(precommitsToDelete) > 0 {
			if err := DeletePrecommittedSectors(st, store, precommitsToDelete...); err != nil {
				return big.Zero(), fmt.Errorf("failed to delete pre-commits: %w", err)
			}
		}

		st.PreCommitDeposits = big.Sub(st.PreCommitDeposits, depositToBurn)
		if st.PreCommitDeposits.LessThan(big.Zero()) {
			return big.Zero(), xerrors.Errorf("pre-commit clean up caused negative deposits: %v", st.PreCommitDeposits)
		}

		// This deposit was locked separately to pledge collateral so there's no pledge change here.
		return depositToBurn, nil

	case *miner15.State:
		st := state.(*miner15.State)
		depositToBurn = abi.NewTokenAmount(0)

		// cleanup expired pre-committed sectors
		cleanUpQ, err := util15.LoadBitfieldQueue(store, st.PreCommittedSectorsCleanUp, st.QuantSpecEveryDeadline(), miner15.PrecommitCleanUpAmtBitwidth)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to load sector expiry queue: %w", err)
		}

		sectors, modified, err := PopUntil(cleanUpQ, currEpoch)
		if err != nil {
			return depositToBurn, xerrors.Errorf("failed to pop expired sectors: %w", err)
		}

		if modified {
			st.PreCommittedSectorsCleanUp, err = cleanUpQ.Root()
			if err != nil {
				return depositToBurn, xerrors.Errorf("failed to save pre commit clean up queue: %w", err)
			}
		}

		var precommitsToDelete []abi.SectorNumber
		if err = sectors.ForEach(func(i uint64) error {
			sectorNo := abi.SectorNumber(i)
			sector, found, err := st.GetPrecommittedSector(store, sectorNo)
			if err != nil {
				return err
			}
			if !found {
				// already committed/deleted
				return nil
			}

			// mark it for deletion
			precommitsToDelete = append(precommitsToDelete, sectorNo)

			// increment deposit to burn
			depositToBurn = big.Add(depositToBurn, sector.PreCommitDeposit)
			return nil
		}); err != nil {
			return big.Zero(), xerrors.Errorf("failed to check pre-commit expiries: %w", err)
		}

		// Actually delete it.
		if len(precommitsToDelete) > 0 {
			if err := DeletePrecommittedSectors(st, store, precommitsToDelete...); err != nil {
				return big.Zero(), fmt.Errorf("failed to delete pre-commits: %w", err)
			}
		}

		st.PreCommitDeposits = big.Sub(st.PreCommitDeposits, depositToBurn)
		if st.PreCommitDeposits.LessThan(big.Zero()) {
			return big.Zero(), xerrors.Errorf("pre-commit clean up caused negative deposits: %v", st.PreCommitDeposits)
		}

		// This deposit was locked separately to pledge collateral so there's no pledge change here.
		return depositToBurn, nil

	default:
		return big.Zero(), fmt.Errorf("CleanUpExpiredPreCommits gets invalid type: %v", state)
	}
}

func PopUntil(queue interface{}, until abi.ChainEpoch) (values bitfield.BitField, modified bool, err error) {
	var poppedValues []bitfield.BitField
	var poppedKeys []uint64

	stopErr := fmt.Errorf("stop")
	switch queue.(type) {
	case util8.BitfieldQueue:
		q := queue.(util8.BitfieldQueue)
		if err = q.ForEach(func(epoch abi.ChainEpoch, bf bitfield.BitField) error {
			if epoch > until {
				return stopErr
			}
			poppedKeys = append(poppedKeys, uint64(epoch))
			poppedValues = append(poppedValues, bf)
			return err
		}); err != nil && err != stopErr {
			return bitfield.BitField{}, false, err
		}

		// Nothing expired.
		if len(poppedKeys) == 0 {
			return bitfield.New(), false, nil
		}

		if err = q.BatchDelete(poppedKeys, true); err != nil {
			return bitfield.BitField{}, false, err
		}
		merged, err := bitfield.MultiMerge(poppedValues...)
		if err != nil {
			return bitfield.BitField{}, false, err
		}

		return merged, true, nil
	case util9.BitfieldQueue:
		q := queue.(util9.BitfieldQueue)
		if err = q.ForEach(func(epoch abi.ChainEpoch, bf bitfield.BitField) error {
			if epoch > until {
				return stopErr
			}
			poppedKeys = append(poppedKeys, uint64(epoch))
			poppedValues = append(poppedValues, bf)
			return err
		}); err != nil && err != stopErr {
			return bitfield.BitField{}, false, err
		}

		// Nothing expired.
		if len(poppedKeys) == 0 {
			return bitfield.New(), false, nil
		}

		if err = q.BatchDelete(poppedKeys, true); err != nil {
			return bitfield.BitField{}, false, err
		}
		merged, err := bitfield.MultiMerge(poppedValues...)
		if err != nil {
			return bitfield.BitField{}, false, err
		}

		return merged, true, nil
	case util10.BitfieldQueue:
		q := queue.(util10.BitfieldQueue)
		if err = q.ForEach(func(epoch abi.ChainEpoch, bf bitfield.BitField) error {
			if epoch > until {
				return stopErr
			}
			poppedKeys = append(poppedKeys, uint64(epoch))
			poppedValues = append(poppedValues, bf)
			return err
		}); err != nil && err != stopErr {
			return bitfield.BitField{}, false, err
		}

		// Nothing expired.
		if len(poppedKeys) == 0 {
			return bitfield.New(), false, nil
		}

		if err = q.BatchDelete(poppedKeys, true); err != nil {
			return bitfield.BitField{}, false, err
		}
		merged, err := bitfield.MultiMerge(poppedValues...)
		if err != nil {
			return bitfield.BitField{}, false, err
		}

		return merged, true, nil
	case util11.BitfieldQueue:
		q := queue.(util11.BitfieldQueue)
		if err = q.ForEach(func(epoch abi.ChainEpoch, bf bitfield.BitField) error {
			if epoch > until {
				return stopErr
			}
			poppedKeys = append(poppedKeys, uint64(epoch))
			poppedValues = append(poppedValues, bf)
			return err
		}); err != nil && err != stopErr {
			return bitfield.BitField{}, false, err
		}

		// Nothing expired.
		if len(poppedKeys) == 0 {
			return bitfield.New(), false, nil
		}

		if err = q.BatchDelete(poppedKeys, true); err != nil {
			return bitfield.BitField{}, false, err
		}
		merged, err := bitfield.MultiMerge(poppedValues...)
		if err != nil {
			return bitfield.BitField{}, false, err
		}

		return merged, true, nil
	case util12.BitfieldQueue:
		q := queue.(util12.BitfieldQueue)
		if err = q.ForEach(func(epoch abi.ChainEpoch, bf bitfield.BitField) error {
			if epoch > until {
				return stopErr
			}
			poppedKeys = append(poppedKeys, uint64(epoch))
			poppedValues = append(poppedValues, bf)
			return err
		}); err != nil && err != stopErr {
			return bitfield.BitField{}, false, err
		}

		// Nothing expired.
		if len(poppedKeys) == 0 {
			return bitfield.New(), false, nil
		}

		if err = q.BatchDelete(poppedKeys, true); err != nil {
			return bitfield.BitField{}, false, err
		}
		merged, err := bitfield.MultiMerge(poppedValues...)
		if err != nil {
			return bitfield.BitField{}, false, err
		}

		return merged, true, nil
	case util13.BitfieldQueue:
		q := queue.(util13.BitfieldQueue)
		if err = q.ForEach(func(epoch abi.ChainEpoch, bf bitfield.BitField) error {
			if epoch > until {
				return stopErr
			}
			poppedKeys = append(poppedKeys, uint64(epoch))
			poppedValues = append(poppedValues, bf)
			return err
		}); err != nil && err != stopErr {
			return bitfield.BitField{}, false, err
		}

		// Nothing expired.
		if len(poppedKeys) == 0 {
			return bitfield.New(), false, nil
		}

		if err = q.BatchDelete(poppedKeys, true); err != nil {
			return bitfield.BitField{}, false, err
		}
		merged, err := bitfield.MultiMerge(poppedValues...)
		if err != nil {
			return bitfield.BitField{}, false, err
		}

		return merged, true, nil
	case util14.BitfieldQueue:
		q := queue.(util14.BitfieldQueue)
		if err = q.ForEach(func(epoch abi.ChainEpoch, bf bitfield.BitField) error {
			if epoch > until {
				return stopErr
			}
			poppedKeys = append(poppedKeys, uint64(epoch))
			poppedValues = append(poppedValues, bf)
			return err
		}); err != nil && err != stopErr {
			return bitfield.BitField{}, false, err
		}

		// Nothing expired.
		if len(poppedKeys) == 0 {
			return bitfield.New(), false, nil
		}

		if err = q.BatchDelete(poppedKeys, true); err != nil {
			return bitfield.BitField{}, false, err
		}
		merged, err := bitfield.MultiMerge(poppedValues...)
		if err != nil {
			return bitfield.BitField{}, false, err
		}

		return merged, true, nil
	case util15.BitfieldQueue:
		q := queue.(util15.BitfieldQueue)
		if err = q.ForEach(func(epoch abi.ChainEpoch, bf bitfield.BitField) error {
			if epoch > until {
				return stopErr
			}
			poppedKeys = append(poppedKeys, uint64(epoch))
			poppedValues = append(poppedValues, bf)
			return err
		}); err != nil && err != stopErr {
			return bitfield.BitField{}, false, err
		}

		// Nothing expired.
		if len(poppedKeys) == 0 {
			return bitfield.New(), false, nil
		}

		if err = q.BatchDelete(poppedKeys, true); err != nil {
			return bitfield.BitField{}, false, err
		}
		merged, err := bitfield.MultiMerge(poppedValues...)
		if err != nil {
			return bitfield.BitField{}, false, err
		}

		return merged, true, nil

	default:
		return bitfield.BitField{}, false, fmt.Errorf("PopUntil gets invalid type: %v", queue)
	}
}

func DeletePrecommittedSectors(state interface{}, store adt.Store, sectorNos ...abi.SectorNumber) error {
	switch state.(type) {
	case *miner8.State:
		st := state.(*miner8.State)
		precommitted, err := adt8.AsMap(store, st.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
		if err != nil {
			return err
		}

		for _, sectorNo := range sectorNos {
			err = precommitted.Delete(miner8.SectorKey(sectorNo))
			if err != nil {
				return xerrors.Errorf("failed to delete precommitment for %v: %w", sectorNo, err)
			}
		}
		st.PreCommittedSectors, err = precommitted.Root()
		return err
	case *miner9.State:
		st := state.(*miner9.State)
		precommitted, err := adt9.AsMap(store, st.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
		if err != nil {
			return err
		}

		for _, sectorNo := range sectorNos {
			err = precommitted.Delete(miner9.SectorKey(sectorNo))
			if err != nil {
				return xerrors.Errorf("failed to delete precommitment for %v: %w", sectorNo, err)
			}
		}
		st.PreCommittedSectors, err = precommitted.Root()
		return err
	case *miner10.State:
		st := state.(*miner10.State)
		precommitted, err := adt10.AsMap(store, st.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
		if err != nil {
			return err
		}

		for _, sectorNo := range sectorNos {
			err = precommitted.Delete(miner10.SectorKey(sectorNo))
			if err != nil {
				return xerrors.Errorf("failed to delete precommitment for %v: %w", sectorNo, err)
			}
		}
		st.PreCommittedSectors, err = precommitted.Root()
		return err
	case *miner11.State:
		st := state.(*miner11.State)
		precommitted, err := adt11.AsMap(store, st.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
		if err != nil {
			return err
		}

		for _, sectorNo := range sectorNos {
			err = precommitted.Delete(miner11.SectorKey(sectorNo))
			if err != nil {
				return xerrors.Errorf("failed to delete precommitment for %v: %w", sectorNo, err)
			}
		}
		st.PreCommittedSectors, err = precommitted.Root()
		return err
	case *miner12.State:
		st := state.(*miner12.State)
		precommitted, err := adt12.AsMap(store, st.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
		if err != nil {
			return err
		}

		for _, sectorNo := range sectorNos {
			err = precommitted.Delete(miner12.SectorKey(sectorNo))
			if err != nil {
				return xerrors.Errorf("failed to delete precommitment for %v: %w", sectorNo, err)
			}
		}
		st.PreCommittedSectors, err = precommitted.Root()
		return err
	case *miner13.State:
		st := state.(*miner13.State)
		precommitted, err := adt13.AsMap(store, st.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
		if err != nil {
			return err
		}

		for _, sectorNo := range sectorNos {
			err = precommitted.Delete(miner13.SectorKey(sectorNo))
			if err != nil {
				return xerrors.Errorf("failed to delete precommitment for %v: %w", sectorNo, err)
			}
		}
		st.PreCommittedSectors, err = precommitted.Root()
		return err
	case *miner14.State:
		st := state.(*miner14.State)
		precommitted, err := adt14.AsMap(store, st.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
		if err != nil {
			return err
		}

		for _, sectorNo := range sectorNos {
			err = precommitted.Delete(miner14.SectorKey(sectorNo))
			if err != nil {
				return xerrors.Errorf("failed to delete precommitment for %v: %w", sectorNo, err)
			}
		}
		st.PreCommittedSectors, err = precommitted.Root()
		return err
	case *miner15.State:
		st := state.(*miner15.State)
		precommitted, err := adt15.AsMap(store, st.PreCommittedSectors, sbuiltin.DefaultHamtBitwidth)
		if err != nil {
			return err
		}

		for _, sectorNo := range sectorNos {
			err = precommitted.Delete(miner15.SectorKey(sectorNo))
			if err != nil {
				return xerrors.Errorf("failed to delete precommitment for %v: %w", sectorNo, err)
			}
		}
		st.PreCommittedSectors, err = precommitted.Root()
		return err

	default:
		return fmt.Errorf("DeletePrecommittedSectors gets invalid type: %v", state)
	}
}
