// Code generated by github.com/londobell/tool/genapi. DO NOT EDIT.

package api

import (
	"context"

	multiquery "github.com/ipfs-force-community/londobell/cmd/londobell-api/multi-query"
	"golang.org/x/xerrors"
)

var ErrNotSupported = xerrors.New("method not supported")

type BellAPIStruct struct {
	Internal struct {
		GetSampleRate func(p0 context.Context) (float64, error) ``

		SegmentDetail func(p0 context.Context, p1 string) (*SegmentDetail, error) ``

		SetSampleRate func(p0 context.Context, p1 float64) (float64, error) ``

		ShutDown func(p0 context.Context) error ``
	}
}

type BellAPIStub struct {
}

type MultiAPIStruct struct {
	Internal struct {
		LoadDBState func(p0 string) (multiquery.DataBaseState, error) ``
	}
}

type MultiAPIStub struct {
}

func (s *BellAPIStruct) GetSampleRate(p0 context.Context) (float64, error) {
	if s.Internal.GetSampleRate == nil {
		return *new(float64), ErrNotSupported
	}
	return s.Internal.GetSampleRate(p0)
}

func (s *BellAPIStub) GetSampleRate(p0 context.Context) (float64, error) {
	return *new(float64), ErrNotSupported
}

func (s *BellAPIStruct) SegmentDetail(p0 context.Context, p1 string) (*SegmentDetail, error) {
	if s.Internal.SegmentDetail == nil {
		return nil, ErrNotSupported
	}
	return s.Internal.SegmentDetail(p0, p1)
}

func (s *BellAPIStub) SegmentDetail(p0 context.Context, p1 string) (*SegmentDetail, error) {
	return nil, ErrNotSupported
}

func (s *BellAPIStruct) SetSampleRate(p0 context.Context, p1 float64) (float64, error) {
	if s.Internal.SetSampleRate == nil {
		return *new(float64), ErrNotSupported
	}
	return s.Internal.SetSampleRate(p0, p1)
}

func (s *BellAPIStub) SetSampleRate(p0 context.Context, p1 float64) (float64, error) {
	return *new(float64), ErrNotSupported
}

func (s *BellAPIStruct) ShutDown(p0 context.Context) error {
	if s.Internal.ShutDown == nil {
		return ErrNotSupported
	}
	return s.Internal.ShutDown(p0)
}

func (s *BellAPIStub) ShutDown(p0 context.Context) error {
	return ErrNotSupported
}

func (s *MultiAPIStruct) LoadDBState(p0 string) (multiquery.DataBaseState, error) {
	if s.Internal.LoadDBState == nil {
		return *new(multiquery.DataBaseState), ErrNotSupported
	}
	return s.Internal.LoadDBState(p0)
}

func (s *MultiAPIStub) LoadDBState(p0 string) (multiquery.DataBaseState, error) {
	return *new(multiquery.DataBaseState), ErrNotSupported
}

var _ BellAPI = new(BellAPIStruct)
var _ MultiAPI = new(MultiAPIStruct)
