// Code generated by github.com/filecoin-project/lotus/gen/api. DO NOT EDIT.

package api

import (
	"context"

	"golang.org/x/xerrors"
)

var ErrNotSupported = xerrors.New("method not supported")

type BellAPIStruct struct {
	Internal struct {
		SegmentDetail func(p0 context.Context, p1 string) (*SegmentDetail, error) ``

		ShutDown func(p0 context.Context) error ``
	}
}

type BellAPIStub struct {
}

func (s *BellAPIStruct) SegmentDetail(p0 context.Context, p1 string) (*SegmentDetail, error) {
	if s.Internal.SegmentDetail == nil {
		return nil, ErrNotSupported
	}
	return s.Internal.SegmentDetail(p0, p1)
}

func (s *BellAPIStub) SegmentDetail(p0 context.Context, p1 string) (*SegmentDetail, error) {
	return nil, ErrNotSupported
}

func (s *BellAPIStruct) ShutDown(p0 context.Context) error {
	if s.Internal.ShutDown == nil {
		return ErrNotSupported
	}
	return s.Internal.ShutDown(p0)
}

func (s *BellAPIStub) ShutDown(p0 context.Context) error {
	return ErrNotSupported
}

var _ BellAPI = new(BellAPIStruct)
