// Code generated by github.com/londobell/tool/genapi. DO NOT EDIT.

package api

import (
	"context"

	"golang.org/x/xerrors"

	segment2 "github.com/ipfs-force-community/londobell/cmd/londobell-api/multi-query/segment"
)

var ErrNotSupported = xerrors.New("method not supported")

type BellAPIStruct struct {
	Internal struct {
		GetSampleRate func(p0 context.Context) (float64, error) ``

		SegmentDetail func(p0 context.Context, p1 string) (*SegmentDetail, error) ``

		SetSampleRate func(p0 context.Context, p1 float64) (float64, error) ``

		ShutDown func(p0 context.Context) error ``
	}
}

type BellAPIStub struct {
}

type MultiAPIStruct struct {
	Internal struct {
		LoadDBInfo func(p0 string) (segment2.Info, error) ``
	}
}

type MultiAPIStub struct {
}

func (s *BellAPIStruct) GetSampleRate(p0 context.Context) (float64, error) {
	if s.Internal.GetSampleRate == nil {
		return *new(float64), ErrNotSupported
	}
	return s.Internal.GetSampleRate(p0)
}

func (s *BellAPIStub) GetSampleRate(p0 context.Context) (float64, error) {
	return *new(float64), ErrNotSupported
}

func (s *BellAPIStruct) SegmentDetail(p0 context.Context, p1 string) (*SegmentDetail, error) {
	if s.Internal.SegmentDetail == nil {
		return nil, ErrNotSupported
	}
	return s.Internal.SegmentDetail(p0, p1)
}

func (s *BellAPIStub) SegmentDetail(p0 context.Context, p1 string) (*SegmentDetail, error) {
	return nil, ErrNotSupported
}

func (s *BellAPIStruct) SetSampleRate(p0 context.Context, p1 float64) (float64, error) {
	if s.Internal.SetSampleRate == nil {
		return *new(float64), ErrNotSupported
	}
	return s.Internal.SetSampleRate(p0, p1)
}

func (s *BellAPIStub) SetSampleRate(p0 context.Context, p1 float64) (float64, error) {
	return *new(float64), ErrNotSupported
}

func (s *BellAPIStruct) ShutDown(p0 context.Context) error {
	if s.Internal.ShutDown == nil {
		return ErrNotSupported
	}
	return s.Internal.ShutDown(p0)
}

func (s *BellAPIStub) ShutDown(p0 context.Context) error {
	return ErrNotSupported
}

func (s *MultiAPIStruct) LoadDBInfo(p0 string) (segment2.Info, error) {
	if s.Internal.LoadDBInfo == nil {
		return *new(segment2.Info), ErrNotSupported
	}
	return s.Internal.LoadDBInfo(p0)
}

func (s *MultiAPIStub) LoadDBInfo(p0 string) (segment2.Info, error) {
	return *new(segment2.Info), ErrNotSupported
}

var _ BellAPI = new(BellAPIStruct)
var _ MultiAPI = new(MultiAPIStruct)
