name: integration_on_pr

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update

      - name: dependencies
        run: sudo apt-get install mesa-opencl-icd ocl-icd-opencl-dev gcc git bzr jq pkg-config curl clang build-essential hwloc libhwloc-dev wget -y

      - uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:

          go-version: '1.21'


      - name: git config
        run: git config --global url."https://ipfs-force-community:${{ secrets.LONDOBELL_AGGREGATER }}@github.com".insteadOf "https://github.com"

      - name: install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2

      - name: build
        if: ${{ success() }}
        run: make build-bell

      - name: lint
        if: ${{ success() }}
        run: make lint

      - name: test
        if: ${{ success() }}
        run: make test

      - name: check-gen
        if: ${{ success() }}
        run: ./tool/scripts/check-gens.sh

      - name: fail_notify
        if: ${{ failure() }}
        env:
          DINGTALK_BOT_ACCESS_TOKEN: ${{ secrets.DINGTALK_BOT_ACCESS_TOKEN }}
          GITHUB_PR_NUM: ${{ github.event.number }}
        run: ./tool/ci/dingtalk_pr_action_failed.sh
